/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationStage } from './applicationStage';
import type { ApplicationStatus } from './applicationStatus';

export interface ApplicationDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  jobLeadId: number | string;
  jobTitle: string;
  companyName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  resumeVariantId: number | string;
  resumeVariantName: string;
  appliedAtUtc: string;
  currentStage: ApplicationStage;
  status: ApplicationStatus;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  expectedSalary: number | string | null;
  /** @nullable */
  expectedSalaryCurrency: string | null;
  /** @nullable */
  noticePeriod: string | null;
  /** @nullable */
  nextStep: string | null;
  /** @nullable */
  nextActionAtUtc: string | null;
  /** @nullable */
  rejectionReason: string | null;
  /** @nullable */
  notes: string | null;
  createdAtUtc: string;
  updatedAtUtc: string;
}
