/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type CompensationFit = typeof CompensationFit[keyof typeof CompensationFit];


export const CompensationFit = {
  Unknown: 'Unknown',
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
} as const;
