/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type CompanyType = typeof CompanyType[keyof typeof CompanyType];


export const CompanyType = {
  Unknown: 'Unknown',
  Product: 'Product',
  Outsourcing: 'Outsourcing',
  Startup: 'Startup',
  Enterprise: 'Enterprise',
  Agency: 'Agency',
} as const;
