/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobActivityOutcome } from './jobActivityOutcome';

export interface CompleteActivityRequest {
  outcome: JobActivityOutcome;
  /** @nullable */
  feedback: string | null;
  /** @nullable */
  notes: string | null;
  createFollowUp: boolean;
}
