/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ConvertToApplicationRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  resumeVariantId: number | string;
  appliedAtUtc: string;
  /** @nullable */
  nextStep: string | null;
  /** @nullable */
  nextActionAtUtc: string | null;
  /** @nullable */
  notes: string | null;
}
