/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Priority } from './priority';

export interface CreateFollowUpTaskRequest {
  title: string;
  /** @nullable */
  description: string | null;
  dueAtUtc: string;
  priority: Priority;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  jobId: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  jobActivityId: number | string | null;
}
