/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { InterviewRoundType } from './interviewRoundType';

export interface CreateInterviewRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  applicationId: number | string;
  roundType: InterviewRoundType;
  scheduledAtUtc: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  durationMinutes: number | string | null;
  /** @nullable */
  interviewerName: string | null;
  /** @nullable */
  interviewerRole: string | null;
  /** @nullable */
  meetingUrl: string | null;
  /** @nullable */
  prepNotes: string | null;
}
