/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmploymentType } from './employmentType';
import type { JobSource } from './jobSource';
import type { JobStatus } from './jobStatus';
import type { Priority } from './priority';
import type { RemoteMode } from './remoteMode';
import type { SalaryPeriod } from './salaryPeriod';

export interface CreateJobRequest {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  companyId: number | string | null;
  title: string;
  status: JobStatus;
  priority: Priority;
  source: JobSource;
  /** @nullable */
  sourceUrl: string | null;
  /** @nullable */
  jobDescription: string | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  locationText: string | null;
  remoteMode: RemoteMode;
  employmentType: EmploymentType;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  salaryMin: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  salaryMax: number | string | null;
  /** @nullable */
  salaryCurrency: string | null;
  salaryPeriod: SalaryPeriod;
  /** @nullable */
  deadlineAtUtc: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  fitScore: number | string | null;
  /** @nullable */
  resumeLabel: string | null;
  /** @nullable */
  resumeAngle: string | null;
  /** @nullable */
  coverLetterNotes: string | null;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  companyName?: string | null;
}
