/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardSummaryDtoActiveJobsByStatus } from './dashboardSummaryDtoActiveJobsByStatus';
import type { OfferDeadlineDto } from './offerDeadlineDto';
import type { StaleJobDto } from './staleJobDto';
import type { UpcomingActivityDto } from './upcomingActivityDto';

export interface DashboardSummaryDto {
  activeJobsByStatus: DashboardSummaryDtoActiveJobsByStatus;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  followUpsDueToday: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  overdueFollowUps: number | string;
  upcomingActivities: UpcomingActivityDto[];
  staleJobs: StaleJobDto[];
  offerDeadlines: OfferDeadlineDto[];
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  daysUntilSearchDeadline: number | string | null;
}
