/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationDto } from './applicationDto';
import type { DeadlineCountdown } from './deadlineCountdown';
import type { FollowUpTaskDto } from './followUpTaskDto';
import type { InterviewDto } from './interviewDto';
import type { JobLeadDto } from './jobLeadDto';
import type { StageCount } from './stageCount';
import type { StatusCount } from './statusCount';

export interface DashboardSummaryDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  activeApplicationCount: number | string;
  leadsByStatus: StatusCount[];
  applicationsByStage: StageCount[];
  followUpsDue: FollowUpTaskDto[];
  overdueFollowUps: FollowUpTaskDto[];
  upcomingInterviews: InterviewDto[];
  highPriorityLeads: JobLeadDto[];
  staleApplications: ApplicationDto[];
  searchDeadline: null | DeadlineCountdown;
}
