/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DeadlineCountdown {
  deadlineUtc: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  daysRemaining: number | string;
}
