/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type EmploymentType = typeof EmploymentType[keyof typeof EmploymentType];


export const EmploymentType = {
  FullTime: 'FullTime',
  PartTime: 'PartTime',
  Contract: 'Contract',
  Freelance: 'Freelance',
  Internship: 'Internship',
} as const;
