/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type FollowUpStatus = typeof FollowUpStatus[keyof typeof FollowUpStatus];


export const FollowUpStatus = {
  Pending: 'Pending',
  Completed: 'Completed',
  Skipped: 'Skipped',
} as const;
