/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FollowUpStatus } from './followUpStatus';
import type { Priority } from './priority';

export interface FollowUpTaskDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  jobId: number | string | null;
  /** @nullable */
  jobTitle: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  jobActivityId: number | string | null;
  /** @nullable */
  jobActivityLabel: string | null;
  title: string;
  /** @nullable */
  description: string | null;
  dueAtUtc: string;
  status: FollowUpStatus;
  priority: Priority;
  createdAtUtc: string;
  updatedAtUtc: string;
}
