/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FollowUpStatus } from './followUpStatus';
import type { Priority } from './priority';
import type { RelatedEntityType } from './relatedEntityType';

export interface FollowUpTaskDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  title: string;
  /** @nullable */
  description: string | null;
  relatedEntityType: RelatedEntityType;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  relatedEntityId: number | string | null;
  dueAtUtc: string;
  status: FollowUpStatus;
  priority: Priority;
  createdAtUtc: string;
  updatedAtUtc: string;
}
