/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { InterviewOutcome } from './interviewOutcome';
import type { InterviewRoundType } from './interviewRoundType';
import type { InterviewStatus } from './interviewStatus';

export interface InterviewDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  applicationId: number | string;
  companyName: string;
  jobTitle: string;
  roundType: InterviewRoundType;
  scheduledAtUtc: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  durationMinutes: number | string | null;
  /** @nullable */
  interviewerName: string | null;
  /** @nullable */
  interviewerRole: string | null;
  /** @nullable */
  meetingUrl: string | null;
  status: InterviewStatus;
  /** @nullable */
  prepNotes: string | null;
  outcome: InterviewOutcome;
  /** @nullable */
  feedback: string | null;
  followUpRequired: boolean;
  /** @nullable */
  followUpAtUtc: string | null;
  createdAtUtc: string;
  updatedAtUtc: string;
}
