/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobActivityOutcome } from './jobActivityOutcome';
import type { JobActivityStatus } from './jobActivityStatus';
import type { JobActivityType } from './jobActivityType';

export interface JobActivityDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  jobId: number | string;
  label: string;
  type: JobActivityType;
  status: JobActivityStatus;
  outcome: JobActivityOutcome;
  /** @nullable */
  scheduledAtUtc: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  durationMinutes: number | string | null;
  /** @nullable */
  contactName: string | null;
  /** @nullable */
  contactRole: string | null;
  /** @nullable */
  meetingUrl: string | null;
  /** @nullable */
  prepNotes: string | null;
  /** @nullable */
  feedback: string | null;
  /** @nullable */
  notes: string | null;
  createdAtUtc: string;
  updatedAtUtc: string;
}
