/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobActivityStatus = typeof JobActivityStatus[keyof typeof JobActivityStatus];


export const JobActivityStatus = {
  Planned: 'Planned',
  Scheduled: 'Scheduled',
  Completed: 'Completed',
  Cancelled: 'Cancelled',
} as const;
