/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobActivityOutcome = typeof JobActivityOutcome[keyof typeof JobActivityOutcome];


export const JobActivityOutcome = {
  Unknown: 'Unknown',
  Waiting: 'Waiting',
  Passed: 'Passed',
  Failed: 'Failed',
} as const;
