/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobAttachmentType } from './jobAttachmentType';

export interface JobAttachmentDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  jobId: number | string;
  type: JobAttachmentType;
  title: string;
  /** @nullable */
  fileName: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  notes: string | null;
  createdAtUtc: string;
  updatedAtUtc: string;
}
