/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobActivityType = typeof JobActivityType[keyof typeof JobActivityType];


export const JobActivityType = {
  Screening: 'Screening',
  Interview: 'Interview',
  Technical: 'Technical',
  SystemDesign: 'SystemDesign',
  Behavioral: 'Behavioral',
  TakeHome: 'TakeHome',
  Assessment: 'Assessment',
  OfferDiscussion: 'OfferDiscussion',
  Other: 'Other',
} as const;
