/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobAttachmentType = typeof JobAttachmentType[keyof typeof JobAttachmentType];


export const JobAttachmentType = {
  Resume: 'Resume',
  CoverLetter: 'CoverLetter',
  JobDescription: 'JobDescription',
  Email: 'Email',
  Screenshot: 'Screenshot',
  Other: 'Other',
} as const;
