/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmploymentType } from './employmentType';
import type { FollowUpTaskDto } from './followUpTaskDto';
import type { JobActivityDto } from './jobActivityDto';
import type { JobAttachmentDto } from './jobAttachmentDto';
import type { JobPropertyDto } from './jobPropertyDto';
import type { JobSource } from './jobSource';
import type { JobStatus } from './jobStatus';
import type { Priority } from './priority';
import type { RemoteMode } from './remoteMode';
import type { SalaryPeriod } from './salaryPeriod';

export interface JobDetailDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  companyId: number | string;
  companyName: string;
  title: string;
  status: JobStatus;
  priority: Priority;
  source: JobSource;
  /** @nullable */
  sourceUrl: string | null;
  /** @nullable */
  jobDescription: string | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  locationText: string | null;
  remoteMode: RemoteMode;
  employmentType: EmploymentType;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  salaryMin: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  salaryMax: number | string | null;
  /** @nullable */
  salaryCurrency: string | null;
  salaryPeriod: SalaryPeriod;
  /** @nullable */
  deadlineAtUtc: string | null;
  /** @nullable */
  appliedAtUtc: string | null;
  /** @nullable */
  lastContactedAtUtc: string | null;
  /** @nullable */
  nextActionAtUtc: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  fitScore: number | string | null;
  /** @nullable */
  resumeLabel: string | null;
  /** @nullable */
  resumeAngle: string | null;
  /** @nullable */
  coverLetterNotes: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  offerSalary: number | string | null;
  /** @nullable */
  offerCurrency: string | null;
  /** @nullable */
  offerDeadlineAtUtc: string | null;
  /** @nullable */
  offerNotes: string | null;
  /** @nullable */
  rejectionReason: string | null;
  /** @nullable */
  notes: string | null;
  createdAtUtc: string;
  updatedAtUtc: string;
  activities: JobActivityDto[];
  properties: JobPropertyDto[];
  attachments: JobAttachmentDto[];
  followUps: FollowUpTaskDto[];
}
