/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobPropertyValueType = typeof JobPropertyValueType[keyof typeof JobPropertyValueType];


export const JobPropertyValueType = {
  Text: 'Text',
  Number: 'Number',
  Date: 'Date',
  Url: 'Url',
  Bool: 'Bool',
} as const;
