/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobPropertyValueType } from './jobPropertyValueType';

export interface JobPropertyDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  jobId: number | string;
  key: string;
  /** @nullable */
  value: string | null;
  valueType: JobPropertyValueType;
  createdAtUtc: string;
  updatedAtUtc: string;
}
