/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobSource = typeof JobSource[keyof typeof JobSource];


export const JobSource = {
  LinkedIn: 'LinkedIn',
  Indeed: 'Indeed',
  Referral: 'Referral',
  CompanySite: 'CompanySite',
  Recruiter: 'Recruiter',
  Other: 'Other',
  Glassdoor: 'Glassdoor',
  Wellfound: 'Wellfound',
  Otta: 'Otta',
  StepStone: 'StepStone',
  Bdjobs: 'Bdjobs',
  Monster: 'Monster',
} as const;
