/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


export const JobStatus = {
  Discovered: 'Discovered',
  Interested: 'Interested',
  Applied: 'Applied',
  Interviewing: 'Interviewing',
  Offered: 'Offered',
  Rejected: 'Rejected',
  Ghosted: 'Ghosted',
  Withdrawn: 'Withdrawn',
  Archived: 'Archived',
} as const;
