/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FollowUpStatus } from './followUpStatus';

export type ListFollowUpTasksParams = {
status?: FollowUpStatus;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
jobId?: number | string;
due?: string;
};
