/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmploymentType } from './employmentType';
import type { JobSource } from './jobSource';
import type { JobStatus } from './jobStatus';
import type { Priority } from './priority';
import type { RemoteMode } from './remoteMode';

export type ListJobsParams = {
Statuses?: JobStatus[];
Source?: JobSource;
RemoteMode?: RemoteMode;
EmploymentType?: EmploymentType;
Countries?: string[];
/**
 * @items.pattern ^-?(?:0|[1-9]\d*)$
 */
CompanyIds?: (number | string)[];
CompanySearch?: string;
Priority?: Priority;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
SalaryMin?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
SalaryMax?: number | string;
AppliedFrom?: string;
AppliedTo?: string;
Search?: string;
};
