/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type MarketType = typeof MarketType[keyof typeof MarketType];


export const MarketType = {
  Unknown: 'Unknown',
  Local: 'Local',
  Remote: 'Remote',
  Hybrid: 'Hybrid',
  International: 'International',
} as const;
