/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { InterviewOutcome } from './interviewOutcome';

export interface MarkInterviewCompletedRequest {
  outcome: InterviewOutcome;
  /** @nullable */
  feedback: string | null;
  followUpRequired: boolean;
  /** @nullable */
  followUpAtUtc: string | null;
}
