/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OfferDeadlineDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  jobId: number | string;
  title: string;
  companyName: string;
  offerDeadlineAtUtc: string;
}
