/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type Priority = typeof Priority[keyof typeof Priority];


export const Priority = {
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
} as const;
