/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type RemoteMode = typeof RemoteMode[keyof typeof RemoteMode];


export const RemoteMode = {
  OnSite: 'OnSite',
  Hybrid: 'Hybrid',
  Remote: 'Remote',
} as const;
