/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ResumeVariantDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  name: string;
  /** @nullable */
  targetRole: string | null;
  /** @nullable */
  summary: string | null;
  /** @nullable */
  notes: string | null;
  isDefault: boolean;
  createdAtUtc: string;
  updatedAtUtc: string;
}
