/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type SalaryPeriod = typeof SalaryPeriod[keyof typeof SalaryPeriod];


export const SalaryPeriod = {
  Annual: 'Annual',
  Monthly: 'Monthly',
  Hourly: 'Hourly',
} as const;
