/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobStatus } from './jobStatus';

export interface StaleJobDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  title: string;
  companyName: string;
  status: JobStatus;
  updatedAtUtc: string;
  /** @nullable */
  nextActionAtUtc: string | null;
}
