/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobLeadStatus } from './jobLeadStatus';

export interface StatusCount {
  status: JobLeadStatus;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count: number | string;
}
