/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export type TimelineEventKind = typeof TimelineEventKind[keyof typeof TimelineEventKind];


export const TimelineEventKind = {
  Transition: 'Transition',
  Activity: 'Activity',
  FollowUp: 'FollowUp',
} as const;
