/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineEventKind } from './timelineEventKind';

export interface TimelineEventDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  kind: TimelineEventKind;
  timestampUtc: string;
  title: string;
  /** @nullable */
  detail: string | null;
  /** @nullable */
  actor: string | null;
}
