/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobStatus } from './jobStatus';

export interface TransitionJobRequest {
  toStatus: JobStatus;
  /** @nullable */
  notes: string | null;
}
