/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpcomingActivityDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  jobId: number | string;
  jobTitle: string;
  companyName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  activityId: number | string;
  activityLabel: string;
  scheduledAtUtc: string;
}
