/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { InterviewRoundType } from './interviewRoundType';
import type { InterviewStatus } from './interviewStatus';

export interface UpdateInterviewRequest {
  roundType: InterviewRoundType;
  scheduledAtUtc: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  durationMinutes: number | string | null;
  /** @nullable */
  interviewerName: string | null;
  /** @nullable */
  interviewerRole: string | null;
  /** @nullable */
  meetingUrl: string | null;
  status: InterviewStatus;
  /** @nullable */
  prepNotes: string | null;
}
