/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateApplicationRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  resumeVariantId: number | string;
  appliedAtUtc: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  expectedSalary: number | string | null;
  /** @nullable */
  expectedSalaryCurrency: string | null;
  /** @nullable */
  noticePeriod: string | null;
  /** @nullable */
  nextStep: string | null;
  /** @nullable */
  nextActionAtUtc: string | null;
  /** @nullable */
  notes: string | null;
}
