/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobAttachmentType } from './jobAttachmentType';

export interface UpdateAttachmentRequest {
  type: JobAttachmentType;
  title: string;
  /** @nullable */
  fileName: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  notes: string | null;
}
