/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CompanyType } from './companyType';
import type { CompensationFit } from './compensationFit';
import type { MarketType } from './marketType';

export interface UpdateCompanyRequest {
  name: string;
  /** @nullable */
  websiteUrl: string | null;
  /** @nullable */
  linkedInUrl: string | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  city: string | null;
  companyType: CompanyType;
  marketType: MarketType;
  compensationFit: CompensationFit;
  /** @nullable */
  notes: string | null;
}
