/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmploymentType } from './employmentType';
import type { JobLeadStatus } from './jobLeadStatus';
import type { JobSource } from './jobSource';
import type { Priority } from './priority';
import type { RemoteMode } from './remoteMode';
import type { SalaryPeriod } from './salaryPeriod';

export interface UpdateJobLeadRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  companyId: number | string;
  title: string;
  source: JobSource;
  /** @nullable */
  sourceUrl: string | null;
  /** @nullable */
  jobDescription: string | null;
  /** @nullable */
  location: string | null;
  remoteMode: RemoteMode;
  employmentType: EmploymentType;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  salaryMin: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  salaryMax: number | string | null;
  /** @nullable */
  salaryCurrency: string | null;
  salaryPeriod: SalaryPeriod;
  priority: Priority;
  status: JobLeadStatus;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  fitScore: number | string | null;
  /** @nullable */
  nextActionAtUtc: string | null;
  /** @nullable */
  deadlineAtUtc: string | null;
  /** @nullable */
  notes: string | null;
}
