/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateResumeVariantRequest {
  name: string;
  /** @nullable */
  targetRole: string | null;
  /** @nullable */
  summary: string | null;
  /** @nullable */
  notes: string | null;
}
