/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobActivityStatus } from './jobActivityStatus';
import type { JobActivityType } from './jobActivityType';

export interface UpdateActivityRequest {
  label: string;
  type: JobActivityType;
  status: JobActivityStatus;
  /** @nullable */
  scheduledAtUtc: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  durationMinutes: number | string | null;
  /** @nullable */
  contactName: string | null;
  /** @nullable */
  contactRole: string | null;
  /** @nullable */
  meetingUrl: string | null;
  /** @nullable */
  prepNotes: string | null;
  /** @nullable */
  notes: string | null;
}
