/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserProfileRequest {
  fullName: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  linkedInUrl: string | null;
  /** @nullable */
  gitHubUrl: string | null;
  /** @nullable */
  portfolioUrl: string | null;
  /** @nullable */
  currentLocation: string | null;
  /** @nullable */
  targetRoles: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  targetSalaryMin: number | string | null;
  /** @nullable */
  targetSalaryCurrency: string | null;
  /** @nullable */
  searchDeadlineUtc: string | null;
  /** @nullable */
  preferredTechStack: string | null;
  /** @nullable */
  careerSummary: string | null;
}
