/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobPropertyValueType } from './jobPropertyValueType';

export interface UpsertPropertyRequest {
  /** @nullable */
  value: string | null;
  valueType: JobPropertyValueType;
}
