/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const listJobsQueryCompanyIdsItemRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const listJobsQuerySalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const listJobsQuerySalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const ListJobsQueryParams = zod.object({
  "Statuses": zod.array(zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived'])).optional(),
  "Source": zod.enum(['LinkedIn', 'Indeed', 'Referral', 'CompanySite', 'Recruiter', 'Other', 'Glassdoor', 'Wellfound', 'Otta', 'StepStone', 'Bdjobs', 'Monster']).optional(),
  "RemoteMode": zod.enum(['OnSite', 'Hybrid', 'Remote']).optional(),
  "EmploymentType": zod.enum(['FullTime', 'PartTime', 'Contract', 'Freelance', 'Internship']).optional(),
  "Countries": zod.array(zod.string()).optional(),
  "CompanyIds": zod.array(zod.union([zod.number(),zod.stringFormat('int32', listJobsQueryCompanyIdsItemRegExpTwo)])).optional(),
  "CompanySearch": zod.string().optional(),
  "Priority": zod.enum(['Low', 'Medium', 'High']).optional(),
  "SalaryMin": zod.union([zod.number(),zod.stringFormat('double', listJobsQuerySalaryMinRegExpTwo)]).optional(),
  "SalaryMax": zod.union([zod.number(),zod.stringFormat('double', listJobsQuerySalaryMaxRegExpTwo)]).optional(),
  "AppliedFrom": zod.iso.datetime({"offset":true}).optional(),
  "AppliedTo": zod.iso.datetime({"offset":true}).optional(),
  "Search": zod.string().optional()
})

export const listJobsResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const listJobsResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const listJobsResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const listJobsResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const listJobsResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const ListJobsResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', listJobsResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', listJobsResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "status": zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "source": zod.enum(['LinkedIn', 'Indeed', 'Referral', 'CompanySite', 'Recruiter', 'Other', 'Glassdoor', 'Wellfound', 'Otta', 'StepStone', 'Bdjobs', 'Monster']),
  "sourceUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "locationText": zod.string().nullable(),
  "remoteMode": zod.enum(['OnSite', 'Hybrid', 'Remote']),
  "employmentType": zod.enum(['FullTime', 'PartTime', 'Contract', 'Freelance', 'Internship']),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', listJobsResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', listJobsResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.enum(['Annual', 'Monthly', 'Hourly']),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "lastContactedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', listJobsResponseFitScoreRegExpTwo)]).nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const ListJobsResponse = zod.array(ListJobsResponseItem)

export const createJobBodyCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobBodySalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobBodySalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobBodyFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateJobBody = zod.object({
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', createJobBodyCompanyIdRegExpTwo)]).nullable(),
  "title": zod.string(),
  "status": zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "source": zod.enum(['LinkedIn', 'Indeed', 'Referral', 'CompanySite', 'Recruiter', 'Other', 'Glassdoor', 'Wellfound', 'Otta', 'StepStone', 'Bdjobs', 'Monster']),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "locationText": zod.string().nullable(),
  "remoteMode": zod.enum(['OnSite', 'Hybrid', 'Remote']),
  "employmentType": zod.enum(['FullTime', 'PartTime', 'Contract', 'Freelance', 'Internship']),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', createJobBodySalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', createJobBodySalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.enum(['Annual', 'Monthly', 'Hourly']),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', createJobBodyFitScoreRegExpTwo)]).nullable(),
  "resumeLabel": zod.string().nullable(),
  "resumeAngle": zod.string().nullable(),
  "coverLetterNotes": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "companyName": zod.string().nullish()
})

export const createJobResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseOfferSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobResponseActivitiesItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseActivitiesItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseActivitiesItemDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponsePropertiesItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponsePropertiesItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseAttachmentsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseAttachmentsItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseFollowUpsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseFollowUpsItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobResponseFollowUpsItemJobActivityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateJobResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "status": zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "source": zod.enum(['LinkedIn', 'Indeed', 'Referral', 'CompanySite', 'Recruiter', 'Other', 'Glassdoor', 'Wellfound', 'Otta', 'StepStone', 'Bdjobs', 'Monster']),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "locationText": zod.string().nullable(),
  "remoteMode": zod.enum(['OnSite', 'Hybrid', 'Remote']),
  "employmentType": zod.enum(['FullTime', 'PartTime', 'Contract', 'Freelance', 'Internship']),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', createJobResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', createJobResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.enum(['Annual', 'Monthly', 'Hourly']),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "lastContactedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseFitScoreRegExpTwo)]).nullable(),
  "resumeLabel": zod.string().nullable(),
  "resumeAngle": zod.string().nullable(),
  "coverLetterNotes": zod.string().nullable(),
  "offerSalary": zod.union([zod.number(),zod.stringFormat('double', createJobResponseOfferSalaryRegExpTwo)]).nullable(),
  "offerCurrency": zod.string().nullable(),
  "offerDeadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "offerNotes": zod.string().nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true}),
  "activities": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseActivitiesItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseActivitiesItemJobIdRegExpTwo)]),
  "label": zod.string(),
  "type": zod.enum(['Screening', 'Interview', 'Technical', 'SystemDesign', 'Behavioral', 'TakeHome', 'Assessment', 'OfferDiscussion', 'Other']),
  "status": zod.enum(['Planned', 'Scheduled', 'Completed', 'Cancelled']),
  "outcome": zod.enum(['Unknown', 'Waiting', 'Passed', 'Failed']),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseActivitiesItemDurationMinutesRegExpTwo)]).nullable(),
  "contactName": zod.string().nullable(),
  "contactRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "prepNotes": zod.string().nullable(),
  "feedback": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "properties": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createJobResponsePropertiesItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', createJobResponsePropertiesItemJobIdRegExpTwo)]),
  "key": zod.string(),
  "value": zod.string().nullable(),
  "valueType": zod.enum(['Text', 'Number', 'Date', 'Url', 'Bool']),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "attachments": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseAttachmentsItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseAttachmentsItemJobIdRegExpTwo)]),
  "type": zod.enum(['Resume', 'CoverLetter', 'JobDescription', 'Email', 'Screenshot', 'Other']),
  "title": zod.string(),
  "fileName": zod.string().nullable(),
  "url": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "followUps": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseFollowUpsItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseFollowUpsItemJobIdRegExpTwo)]).nullable(),
  "jobTitle": zod.string().nullable(),
  "jobActivityId": zod.union([zod.number(),zod.stringFormat('int32', createJobResponseFollowUpsItemJobActivityIdRegExpTwo)]).nullable(),
  "jobActivityLabel": zod.string().nullable(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "status": zod.enum(['Pending', 'Completed', 'Skipped']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
}))
})

export const GetJobParams = zod.object({
  "id": zod.number()
})

export const getJobResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseOfferSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobResponseActivitiesItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseActivitiesItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseActivitiesItemDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponsePropertiesItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponsePropertiesItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseAttachmentsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseAttachmentsItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseFollowUpsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseFollowUpsItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobResponseFollowUpsItemJobActivityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetJobResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "status": zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "source": zod.enum(['LinkedIn', 'Indeed', 'Referral', 'CompanySite', 'Recruiter', 'Other', 'Glassdoor', 'Wellfound', 'Otta', 'StepStone', 'Bdjobs', 'Monster']),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "locationText": zod.string().nullable(),
  "remoteMode": zod.enum(['OnSite', 'Hybrid', 'Remote']),
  "employmentType": zod.enum(['FullTime', 'PartTime', 'Contract', 'Freelance', 'Internship']),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', getJobResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', getJobResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.enum(['Annual', 'Monthly', 'Hourly']),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "lastContactedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseFitScoreRegExpTwo)]).nullable(),
  "resumeLabel": zod.string().nullable(),
  "resumeAngle": zod.string().nullable(),
  "coverLetterNotes": zod.string().nullable(),
  "offerSalary": zod.union([zod.number(),zod.stringFormat('double', getJobResponseOfferSalaryRegExpTwo)]).nullable(),
  "offerCurrency": zod.string().nullable(),
  "offerDeadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "offerNotes": zod.string().nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true}),
  "activities": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseActivitiesItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseActivitiesItemJobIdRegExpTwo)]),
  "label": zod.string(),
  "type": zod.enum(['Screening', 'Interview', 'Technical', 'SystemDesign', 'Behavioral', 'TakeHome', 'Assessment', 'OfferDiscussion', 'Other']),
  "status": zod.enum(['Planned', 'Scheduled', 'Completed', 'Cancelled']),
  "outcome": zod.enum(['Unknown', 'Waiting', 'Passed', 'Failed']),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseActivitiesItemDurationMinutesRegExpTwo)]).nullable(),
  "contactName": zod.string().nullable(),
  "contactRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "prepNotes": zod.string().nullable(),
  "feedback": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "properties": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobResponsePropertiesItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', getJobResponsePropertiesItemJobIdRegExpTwo)]),
  "key": zod.string(),
  "value": zod.string().nullable(),
  "valueType": zod.enum(['Text', 'Number', 'Date', 'Url', 'Bool']),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "attachments": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseAttachmentsItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseAttachmentsItemJobIdRegExpTwo)]),
  "type": zod.enum(['Resume', 'CoverLetter', 'JobDescription', 'Email', 'Screenshot', 'Other']),
  "title": zod.string(),
  "fileName": zod.string().nullable(),
  "url": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "followUps": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseFollowUpsItemIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseFollowUpsItemJobIdRegExpTwo)]).nullable(),
  "jobTitle": zod.string().nullable(),
  "jobActivityId": zod.union([zod.number(),zod.stringFormat('int32', getJobResponseFollowUpsItemJobActivityIdRegExpTwo)]).nullable(),
  "jobActivityLabel": zod.string().nullable(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "status": zod.enum(['Pending', 'Completed', 'Skipped']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
}))
})

export const UpdateJobParams = zod.object({
  "id": zod.number()
})

export const updateJobBodyCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateJobBodySalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const updateJobBodySalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const updateJobBodyFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateJobBodyOfferSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const UpdateJobBody = zod.object({
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', updateJobBodyCompanyIdRegExpTwo)]),
  "title": zod.string(),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "source": zod.enum(['LinkedIn', 'Indeed', 'Referral', 'CompanySite', 'Recruiter', 'Other', 'Glassdoor', 'Wellfound', 'Otta', 'StepStone', 'Bdjobs', 'Monster']),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "locationText": zod.string().nullable(),
  "remoteMode": zod.enum(['OnSite', 'Hybrid', 'Remote']),
  "employmentType": zod.enum(['FullTime', 'PartTime', 'Contract', 'Freelance', 'Internship']),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', updateJobBodySalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', updateJobBodySalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.enum(['Annual', 'Monthly', 'Hourly']),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "lastContactedAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', updateJobBodyFitScoreRegExpTwo)]).nullable(),
  "resumeLabel": zod.string().nullable(),
  "resumeAngle": zod.string().nullable(),
  "coverLetterNotes": zod.string().nullable(),
  "offerSalary": zod.union([zod.number(),zod.stringFormat('double', updateJobBodyOfferSalaryRegExpTwo)]).nullable(),
  "offerCurrency": zod.string().nullable(),
  "offerDeadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "offerNotes": zod.string().nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const UpdateJobResponse = zod.unknown()

export const DeleteJobParams = zod.object({
  "id": zod.number()
})

export const DeleteJobResponse = zod.unknown()

export const TransitionJobParams = zod.object({
  "id": zod.number()
})

export const TransitionJobBody = zod.object({
  "toStatus": zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived']),
  "notes": zod.string().nullable()
})

export const TransitionJobResponse = zod.unknown()

export const GetJobTimelineParams = zod.object({
  "id": zod.number()
})

export const getJobTimelineResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetJobTimelineResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobTimelineResponseIdRegExpTwo)]),
  "kind": zod.enum(['Transition', 'Activity', 'FollowUp']),
  "timestampUtc": zod.iso.datetime({"offset":true}),
  "title": zod.string(),
  "detail": zod.string().nullable(),
  "actor": zod.string().nullable()
})
export const GetJobTimelineResponse = zod.array(GetJobTimelineResponseItem)

export const AddJobActivityParams = zod.object({
  "id": zod.number()
})

export const addJobActivityBodyDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const AddJobActivityBody = zod.object({
  "label": zod.string(),
  "type": zod.enum(['Screening', 'Interview', 'Technical', 'SystemDesign', 'Behavioral', 'TakeHome', 'Assessment', 'OfferDiscussion', 'Other']),
  "status": zod.enum(['Planned', 'Scheduled', 'Completed', 'Cancelled']),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', addJobActivityBodyDurationMinutesRegExpTwo)]).nullable(),
  "contactName": zod.string().nullable(),
  "contactRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "prepNotes": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const AddJobActivityResponse = zod.unknown()

export const UpdateJobActivityParams = zod.object({
  "id": zod.number(),
  "activityId": zod.number()
})

export const updateJobActivityBodyDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateJobActivityBody = zod.object({
  "label": zod.string(),
  "type": zod.enum(['Screening', 'Interview', 'Technical', 'SystemDesign', 'Behavioral', 'TakeHome', 'Assessment', 'OfferDiscussion', 'Other']),
  "status": zod.enum(['Planned', 'Scheduled', 'Completed', 'Cancelled']),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', updateJobActivityBodyDurationMinutesRegExpTwo)]).nullable(),
  "contactName": zod.string().nullable(),
  "contactRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "prepNotes": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const UpdateJobActivityResponse = zod.unknown()

export const DeleteJobActivityParams = zod.object({
  "id": zod.number(),
  "activityId": zod.number()
})

export const DeleteJobActivityResponse = zod.unknown()

export const CompleteJobActivityParams = zod.object({
  "id": zod.number(),
  "activityId": zod.number()
})

export const CompleteJobActivityBody = zod.object({
  "outcome": zod.enum(['Unknown', 'Waiting', 'Passed', 'Failed']),
  "feedback": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createFollowUp": zod.boolean()
})

export const CompleteJobActivityResponse = zod.unknown()

export const AddJobAttachmentParams = zod.object({
  "id": zod.number()
})

export const AddJobAttachmentBody = zod.object({
  "type": zod.enum(['Resume', 'CoverLetter', 'JobDescription', 'Email', 'Screenshot', 'Other']),
  "title": zod.string(),
  "fileName": zod.string().nullable(),
  "url": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const AddJobAttachmentResponse = zod.unknown()

export const UpdateJobAttachmentParams = zod.object({
  "id": zod.number(),
  "attachmentId": zod.number()
})

export const UpdateJobAttachmentBody = zod.object({
  "type": zod.enum(['Resume', 'CoverLetter', 'JobDescription', 'Email', 'Screenshot', 'Other']),
  "title": zod.string(),
  "fileName": zod.string().nullable(),
  "url": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const UpdateJobAttachmentResponse = zod.unknown()

export const DeleteJobAttachmentParams = zod.object({
  "id": zod.number(),
  "attachmentId": zod.number()
})

export const DeleteJobAttachmentResponse = zod.unknown()

export const UpsertJobPropertyParams = zod.object({
  "id": zod.number(),
  "key": zod.string()
})

export const UpsertJobPropertyBody = zod.object({
  "value": zod.string().nullable(),
  "valueType": zod.enum(['Text', 'Number', 'Date', 'Url', 'Bool'])
})

export const UpsertJobPropertyResponse = zod.unknown()

export const DeleteJobPropertyParams = zod.object({
  "id": zod.number(),
  "key": zod.string()
})

export const DeleteJobPropertyResponse = zod.unknown()

export const CreateJobFollowUpParams = zod.object({
  "id": zod.number()
})

export const createJobFollowUpBodyJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobFollowUpBodyJobActivityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateJobFollowUpBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', createJobFollowUpBodyJobIdRegExpTwo)]).nullable(),
  "jobActivityId": zod.union([zod.number(),zod.stringFormat('int32', createJobFollowUpBodyJobActivityIdRegExpTwo)]).nullable()
})

export const CreateJobFollowUpResponse = zod.unknown()

