/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddAttachmentRequest,
  CompleteActivityRequest,
  CreateActivityRequest,
  CreateFollowUpTaskRequest,
  CreateJobRequest,
  JobDetailDto,
  JobDto,
  ListJobsParams,
  SetJobPriorityRequest,
  TimelineEventDto,
  TransitionJobRequest,
  UpdateActivityRequest,
  UpdateAttachmentRequest,
  UpdateJobRequest,
  UpsertPropertyRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listJobsResponse200 = {
  data: JobDto[]
  status: 200
}

export type listJobsResponseSuccess = (listJobsResponse200) & {
  headers: Headers;
};
;

export type listJobsResponse = (listJobsResponseSuccess)

export const getListJobsUrl = (params?: ListJobsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/jobs?${stringifiedParams}` : `/api/jobs`
}

export const listJobs = async (params?: ListJobsParams, options?: RequestInit): Promise<listJobsResponse> => {

  return apiClient<listJobsResponse>(getListJobsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListJobsQueryKey = (params?: ListJobsParams,) => {
    return [
    `/api/jobs`, ...(params ? [params] : [])
    ] as const;
    }


export const getListJobsQueryOptions = <TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(params?: ListJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJobsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJobs>>> = ({ signal }) => listJobs(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listJobs>>>
export type ListJobsQueryError = unknown


export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
 params: undefined |  ListJobsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJobs>>,
          TError,
          Awaited<ReturnType<typeof listJobs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
 params?: ListJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJobs>>,
          TError,
          Awaited<ReturnType<typeof listJobs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
 params?: ListJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
 params?: ListJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJobsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createJobResponse201 = {
  data: JobDetailDto
  status: 201
}

export type createJobResponseSuccess = (createJobResponse201) & {
  headers: Headers;
};
;

export type createJobResponse = (createJobResponseSuccess)

export const getCreateJobUrl = () => {




  return `/api/jobs`
}

export const createJob = async (createJobRequest: CreateJobRequest, options?: RequestInit): Promise<createJobResponse> => {

  return apiClient<createJobResponse>(getCreateJobUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createJobRequest)
  }
);}





export const getCreateJobMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError,{data: CreateJobRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError,{data: CreateJobRequest}, TContext> => {

const mutationKey = ['createJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJob>>, {data: CreateJobRequest}> = (props) => {
          const {data} = props ?? {};

          return  createJob(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateJobMutationResult = NonNullable<Awaited<ReturnType<typeof createJob>>>
    export type CreateJobMutationBody = CreateJobRequest
    export type CreateJobMutationError = unknown

    export const useCreateJob = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError,{data: CreateJobRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createJob>>,
        TError,
        {data: CreateJobRequest},
        TContext
      > => {
      return useMutation(getCreateJobMutationOptions(options), queryClient);
    }
    export type getJobResponse200 = {
  data: JobDetailDto
  status: 200
}

export type getJobResponse404 = {
  data: void
  status: 404
}

export type getJobResponseSuccess = (getJobResponse200) & {
  headers: Headers;
};
export type getJobResponseError = (getJobResponse404) & {
  headers: Headers;
};

export type getJobResponse = (getJobResponseSuccess | getJobResponseError)

export const getGetJobUrl = (id: number,) => {




  return `/api/jobs/${id}`
}

export const getJob = async (id: number, options?: RequestInit): Promise<getJobResponse> => {

  return apiClient<getJobResponse>(getGetJobUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobQueryKey = (id: number,) => {
    return [
    `/api/jobs/${id}`
    ] as const;
    }


export const getGetJobQueryOptions = <TData = Awaited<ReturnType<typeof getJob>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJob>>> = ({ signal }) => getJob(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobQueryResult = NonNullable<Awaited<ReturnType<typeof getJob>>>
export type GetJobQueryError = void


export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJob>>,
          TError,
          Awaited<ReturnType<typeof getJob>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJob>>,
          TError,
          Awaited<ReturnType<typeof getJob>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateJobResponse200 = {
  data: void
  status: 200
}

export type updateJobResponseSuccess = (updateJobResponse200) & {
  headers: Headers;
};
;

export type updateJobResponse = (updateJobResponseSuccess)

export const getUpdateJobUrl = (id: number,) => {




  return `/api/jobs/${id}`
}

export const updateJob = async (id: number,
    updateJobRequest: UpdateJobRequest, options?: RequestInit): Promise<updateJobResponse> => {

  return apiClient<updateJobResponse>(getUpdateJobUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateJobRequest)
  }
);}





export const getUpdateJobMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError,{id: number;data: UpdateJobRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError,{id: number;data: UpdateJobRequest}, TContext> => {

const mutationKey = ['updateJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateJob>>, {id: number;data: UpdateJobRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateJob(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateJobMutationResult = NonNullable<Awaited<ReturnType<typeof updateJob>>>
    export type UpdateJobMutationBody = UpdateJobRequest
    export type UpdateJobMutationError = unknown

    export const useUpdateJob = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError,{id: number;data: UpdateJobRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateJob>>,
        TError,
        {id: number;data: UpdateJobRequest},
        TContext
      > => {
      return useMutation(getUpdateJobMutationOptions(options), queryClient);
    }
    export type deleteJobResponse200 = {
  data: void
  status: 200
}

export type deleteJobResponseSuccess = (deleteJobResponse200) & {
  headers: Headers;
};
;

export type deleteJobResponse = (deleteJobResponseSuccess)

export const getDeleteJobUrl = (id: number,) => {




  return `/api/jobs/${id}`
}

export const deleteJob = async (id: number, options?: RequestInit): Promise<deleteJobResponse> => {

  return apiClient<deleteJobResponse>(getDeleteJobUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteJobMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJob>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJob>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJob>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteJob(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJob>>>

    export type DeleteJobMutationError = unknown

    export const useDeleteJob = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJob>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteJob>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteJobMutationOptions(options), queryClient);
    }
    export type transitionJobResponse200 = {
  data: void
  status: 200
}

export type transitionJobResponseSuccess = (transitionJobResponse200) & {
  headers: Headers;
};
;

export type transitionJobResponse = (transitionJobResponseSuccess)

export const getTransitionJobUrl = (id: number,) => {




  return `/api/jobs/${id}/transition`
}

export const transitionJob = async (id: number,
    transitionJobRequest: TransitionJobRequest, options?: RequestInit): Promise<transitionJobResponse> => {

  return apiClient<transitionJobResponse>(getTransitionJobUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(transitionJobRequest)
  }
);}





export const getTransitionJobMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transitionJob>>, TError,{id: number;data: TransitionJobRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof transitionJob>>, TError,{id: number;data: TransitionJobRequest}, TContext> => {

const mutationKey = ['transitionJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transitionJob>>, {id: number;data: TransitionJobRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  transitionJob(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TransitionJobMutationResult = NonNullable<Awaited<ReturnType<typeof transitionJob>>>
    export type TransitionJobMutationBody = TransitionJobRequest
    export type TransitionJobMutationError = unknown

    export const useTransitionJob = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transitionJob>>, TError,{id: number;data: TransitionJobRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof transitionJob>>,
        TError,
        {id: number;data: TransitionJobRequest},
        TContext
      > => {
      return useMutation(getTransitionJobMutationOptions(options), queryClient);
    }
    export type getJobTimelineResponse200 = {
  data: TimelineEventDto[]
  status: 200
}

export type getJobTimelineResponseSuccess = (getJobTimelineResponse200) & {
  headers: Headers;
};
;

export type getJobTimelineResponse = (getJobTimelineResponseSuccess)

export const getGetJobTimelineUrl = (id: number,) => {




  return `/api/jobs/${id}/timeline`
}

export const getJobTimeline = async (id: number, options?: RequestInit): Promise<getJobTimelineResponse> => {

  return apiClient<getJobTimelineResponse>(getGetJobTimelineUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobTimelineQueryKey = (id: number,) => {
    return [
    `/api/jobs/${id}/timeline`
    ] as const;
    }


export const getGetJobTimelineQueryOptions = <TData = Awaited<ReturnType<typeof getJobTimeline>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobTimeline>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobTimelineQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobTimeline>>> = ({ signal }) => getJobTimeline(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobTimeline>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobTimelineQueryResult = NonNullable<Awaited<ReturnType<typeof getJobTimeline>>>
export type GetJobTimelineQueryError = unknown


export function useGetJobTimeline<TData = Awaited<ReturnType<typeof getJobTimeline>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobTimeline>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobTimeline>>,
          TError,
          Awaited<ReturnType<typeof getJobTimeline>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobTimeline<TData = Awaited<ReturnType<typeof getJobTimeline>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobTimeline>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobTimeline>>,
          TError,
          Awaited<ReturnType<typeof getJobTimeline>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobTimeline<TData = Awaited<ReturnType<typeof getJobTimeline>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobTimeline>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetJobTimeline<TData = Awaited<ReturnType<typeof getJobTimeline>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobTimeline>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobTimelineQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type addJobActivityResponse200 = {
  data: void
  status: 200
}

export type addJobActivityResponseSuccess = (addJobActivityResponse200) & {
  headers: Headers;
};
;

export type addJobActivityResponse = (addJobActivityResponseSuccess)

export const getAddJobActivityUrl = (id: number,) => {




  return `/api/jobs/${id}/activities`
}

export const addJobActivity = async (id: number,
    createActivityRequest: CreateActivityRequest, options?: RequestInit): Promise<addJobActivityResponse> => {

  return apiClient<addJobActivityResponse>(getAddJobActivityUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createActivityRequest)
  }
);}





export const getAddJobActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addJobActivity>>, TError,{id: number;data: CreateActivityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof addJobActivity>>, TError,{id: number;data: CreateActivityRequest}, TContext> => {

const mutationKey = ['addJobActivity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addJobActivity>>, {id: number;data: CreateActivityRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  addJobActivity(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddJobActivityMutationResult = NonNullable<Awaited<ReturnType<typeof addJobActivity>>>
    export type AddJobActivityMutationBody = CreateActivityRequest
    export type AddJobActivityMutationError = unknown

    export const useAddJobActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addJobActivity>>, TError,{id: number;data: CreateActivityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addJobActivity>>,
        TError,
        {id: number;data: CreateActivityRequest},
        TContext
      > => {
      return useMutation(getAddJobActivityMutationOptions(options), queryClient);
    }
    export type updateJobActivityResponse200 = {
  data: void
  status: 200
}

export type updateJobActivityResponseSuccess = (updateJobActivityResponse200) & {
  headers: Headers;
};
;

export type updateJobActivityResponse = (updateJobActivityResponseSuccess)

export const getUpdateJobActivityUrl = (id: number,
    activityId: number,) => {




  return `/api/jobs/${id}/activities/${activityId}`
}

export const updateJobActivity = async (id: number,
    activityId: number,
    updateActivityRequest: UpdateActivityRequest, options?: RequestInit): Promise<updateJobActivityResponse> => {

  return apiClient<updateJobActivityResponse>(getUpdateJobActivityUrl(id,activityId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateActivityRequest)
  }
);}





export const getUpdateJobActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJobActivity>>, TError,{id: number;activityId: number;data: UpdateActivityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateJobActivity>>, TError,{id: number;activityId: number;data: UpdateActivityRequest}, TContext> => {

const mutationKey = ['updateJobActivity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateJobActivity>>, {id: number;activityId: number;data: UpdateActivityRequest}> = (props) => {
          const {id,activityId,data} = props ?? {};

          return  updateJobActivity(id,activityId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateJobActivityMutationResult = NonNullable<Awaited<ReturnType<typeof updateJobActivity>>>
    export type UpdateJobActivityMutationBody = UpdateActivityRequest
    export type UpdateJobActivityMutationError = unknown

    export const useUpdateJobActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJobActivity>>, TError,{id: number;activityId: number;data: UpdateActivityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateJobActivity>>,
        TError,
        {id: number;activityId: number;data: UpdateActivityRequest},
        TContext
      > => {
      return useMutation(getUpdateJobActivityMutationOptions(options), queryClient);
    }
    export type deleteJobActivityResponse200 = {
  data: void
  status: 200
}

export type deleteJobActivityResponseSuccess = (deleteJobActivityResponse200) & {
  headers: Headers;
};
;

export type deleteJobActivityResponse = (deleteJobActivityResponseSuccess)

export const getDeleteJobActivityUrl = (id: number,
    activityId: number,) => {




  return `/api/jobs/${id}/activities/${activityId}`
}

export const deleteJobActivity = async (id: number,
    activityId: number, options?: RequestInit): Promise<deleteJobActivityResponse> => {

  return apiClient<deleteJobActivityResponse>(getDeleteJobActivityUrl(id,activityId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteJobActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobActivity>>, TError,{id: number;activityId: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJobActivity>>, TError,{id: number;activityId: number}, TContext> => {

const mutationKey = ['deleteJobActivity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJobActivity>>, {id: number;activityId: number}> = (props) => {
          const {id,activityId} = props ?? {};

          return  deleteJobActivity(id,activityId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobActivityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJobActivity>>>

    export type DeleteJobActivityMutationError = unknown

    export const useDeleteJobActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobActivity>>, TError,{id: number;activityId: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteJobActivity>>,
        TError,
        {id: number;activityId: number},
        TContext
      > => {
      return useMutation(getDeleteJobActivityMutationOptions(options), queryClient);
    }
    export type completeJobActivityResponse200 = {
  data: void
  status: 200
}

export type completeJobActivityResponseSuccess = (completeJobActivityResponse200) & {
  headers: Headers;
};
;

export type completeJobActivityResponse = (completeJobActivityResponseSuccess)

export const getCompleteJobActivityUrl = (id: number,
    activityId: number,) => {




  return `/api/jobs/${id}/activities/${activityId}/complete`
}

export const completeJobActivity = async (id: number,
    activityId: number,
    completeActivityRequest: CompleteActivityRequest, options?: RequestInit): Promise<completeJobActivityResponse> => {

  return apiClient<completeJobActivityResponse>(getCompleteJobActivityUrl(id,activityId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(completeActivityRequest)
  }
);}





export const getCompleteJobActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeJobActivity>>, TError,{id: number;activityId: number;data: CompleteActivityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof completeJobActivity>>, TError,{id: number;activityId: number;data: CompleteActivityRequest}, TContext> => {

const mutationKey = ['completeJobActivity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeJobActivity>>, {id: number;activityId: number;data: CompleteActivityRequest}> = (props) => {
          const {id,activityId,data} = props ?? {};

          return  completeJobActivity(id,activityId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteJobActivityMutationResult = NonNullable<Awaited<ReturnType<typeof completeJobActivity>>>
    export type CompleteJobActivityMutationBody = CompleteActivityRequest
    export type CompleteJobActivityMutationError = unknown

    export const useCompleteJobActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeJobActivity>>, TError,{id: number;activityId: number;data: CompleteActivityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeJobActivity>>,
        TError,
        {id: number;activityId: number;data: CompleteActivityRequest},
        TContext
      > => {
      return useMutation(getCompleteJobActivityMutationOptions(options), queryClient);
    }
    export type addJobAttachmentResponse200 = {
  data: void
  status: 200
}

export type addJobAttachmentResponseSuccess = (addJobAttachmentResponse200) & {
  headers: Headers;
};
;

export type addJobAttachmentResponse = (addJobAttachmentResponseSuccess)

export const getAddJobAttachmentUrl = (id: number,) => {




  return `/api/jobs/${id}/attachments`
}

export const addJobAttachment = async (id: number,
    addAttachmentRequest: AddAttachmentRequest, options?: RequestInit): Promise<addJobAttachmentResponse> => {

  return apiClient<addJobAttachmentResponse>(getAddJobAttachmentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addAttachmentRequest)
  }
);}





export const getAddJobAttachmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addJobAttachment>>, TError,{id: number;data: AddAttachmentRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof addJobAttachment>>, TError,{id: number;data: AddAttachmentRequest}, TContext> => {

const mutationKey = ['addJobAttachment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addJobAttachment>>, {id: number;data: AddAttachmentRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  addJobAttachment(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddJobAttachmentMutationResult = NonNullable<Awaited<ReturnType<typeof addJobAttachment>>>
    export type AddJobAttachmentMutationBody = AddAttachmentRequest
    export type AddJobAttachmentMutationError = unknown

    export const useAddJobAttachment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addJobAttachment>>, TError,{id: number;data: AddAttachmentRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addJobAttachment>>,
        TError,
        {id: number;data: AddAttachmentRequest},
        TContext
      > => {
      return useMutation(getAddJobAttachmentMutationOptions(options), queryClient);
    }
    export type updateJobAttachmentResponse200 = {
  data: void
  status: 200
}

export type updateJobAttachmentResponseSuccess = (updateJobAttachmentResponse200) & {
  headers: Headers;
};
;

export type updateJobAttachmentResponse = (updateJobAttachmentResponseSuccess)

export const getUpdateJobAttachmentUrl = (id: number,
    attachmentId: number,) => {




  return `/api/jobs/${id}/attachments/${attachmentId}`
}

export const updateJobAttachment = async (id: number,
    attachmentId: number,
    updateAttachmentRequest: UpdateAttachmentRequest, options?: RequestInit): Promise<updateJobAttachmentResponse> => {

  return apiClient<updateJobAttachmentResponse>(getUpdateJobAttachmentUrl(id,attachmentId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAttachmentRequest)
  }
);}





export const getUpdateJobAttachmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJobAttachment>>, TError,{id: number;attachmentId: number;data: UpdateAttachmentRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateJobAttachment>>, TError,{id: number;attachmentId: number;data: UpdateAttachmentRequest}, TContext> => {

const mutationKey = ['updateJobAttachment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateJobAttachment>>, {id: number;attachmentId: number;data: UpdateAttachmentRequest}> = (props) => {
          const {id,attachmentId,data} = props ?? {};

          return  updateJobAttachment(id,attachmentId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateJobAttachmentMutationResult = NonNullable<Awaited<ReturnType<typeof updateJobAttachment>>>
    export type UpdateJobAttachmentMutationBody = UpdateAttachmentRequest
    export type UpdateJobAttachmentMutationError = unknown

    export const useUpdateJobAttachment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJobAttachment>>, TError,{id: number;attachmentId: number;data: UpdateAttachmentRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateJobAttachment>>,
        TError,
        {id: number;attachmentId: number;data: UpdateAttachmentRequest},
        TContext
      > => {
      return useMutation(getUpdateJobAttachmentMutationOptions(options), queryClient);
    }
    export type deleteJobAttachmentResponse200 = {
  data: void
  status: 200
}

export type deleteJobAttachmentResponseSuccess = (deleteJobAttachmentResponse200) & {
  headers: Headers;
};
;

export type deleteJobAttachmentResponse = (deleteJobAttachmentResponseSuccess)

export const getDeleteJobAttachmentUrl = (id: number,
    attachmentId: number,) => {




  return `/api/jobs/${id}/attachments/${attachmentId}`
}

export const deleteJobAttachment = async (id: number,
    attachmentId: number, options?: RequestInit): Promise<deleteJobAttachmentResponse> => {

  return apiClient<deleteJobAttachmentResponse>(getDeleteJobAttachmentUrl(id,attachmentId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteJobAttachmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobAttachment>>, TError,{id: number;attachmentId: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJobAttachment>>, TError,{id: number;attachmentId: number}, TContext> => {

const mutationKey = ['deleteJobAttachment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJobAttachment>>, {id: number;attachmentId: number}> = (props) => {
          const {id,attachmentId} = props ?? {};

          return  deleteJobAttachment(id,attachmentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobAttachmentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJobAttachment>>>

    export type DeleteJobAttachmentMutationError = unknown

    export const useDeleteJobAttachment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobAttachment>>, TError,{id: number;attachmentId: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteJobAttachment>>,
        TError,
        {id: number;attachmentId: number},
        TContext
      > => {
      return useMutation(getDeleteJobAttachmentMutationOptions(options), queryClient);
    }
    export type upsertJobPropertyResponse200 = {
  data: void
  status: 200
}

export type upsertJobPropertyResponseSuccess = (upsertJobPropertyResponse200) & {
  headers: Headers;
};
;

export type upsertJobPropertyResponse = (upsertJobPropertyResponseSuccess)

export const getUpsertJobPropertyUrl = (id: number,
    key: string,) => {




  return `/api/jobs/${id}/properties/${key}`
}

export const upsertJobProperty = async (id: number,
    key: string,
    upsertPropertyRequest: UpsertPropertyRequest, options?: RequestInit): Promise<upsertJobPropertyResponse> => {

  return apiClient<upsertJobPropertyResponse>(getUpsertJobPropertyUrl(id,key),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertPropertyRequest)
  }
);}





export const getUpsertJobPropertyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertJobProperty>>, TError,{id: number;key: string;data: UpsertPropertyRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertJobProperty>>, TError,{id: number;key: string;data: UpsertPropertyRequest}, TContext> => {

const mutationKey = ['upsertJobProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertJobProperty>>, {id: number;key: string;data: UpsertPropertyRequest}> = (props) => {
          const {id,key,data} = props ?? {};

          return  upsertJobProperty(id,key,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpsertJobPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof upsertJobProperty>>>
    export type UpsertJobPropertyMutationBody = UpsertPropertyRequest
    export type UpsertJobPropertyMutationError = unknown

    export const useUpsertJobProperty = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertJobProperty>>, TError,{id: number;key: string;data: UpsertPropertyRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertJobProperty>>,
        TError,
        {id: number;key: string;data: UpsertPropertyRequest},
        TContext
      > => {
      return useMutation(getUpsertJobPropertyMutationOptions(options), queryClient);
    }
    export type deleteJobPropertyResponse200 = {
  data: void
  status: 200
}

export type deleteJobPropertyResponseSuccess = (deleteJobPropertyResponse200) & {
  headers: Headers;
};
;

export type deleteJobPropertyResponse = (deleteJobPropertyResponseSuccess)

export const getDeleteJobPropertyUrl = (id: number,
    key: string,) => {




  return `/api/jobs/${id}/properties/${key}`
}

export const deleteJobProperty = async (id: number,
    key: string, options?: RequestInit): Promise<deleteJobPropertyResponse> => {

  return apiClient<deleteJobPropertyResponse>(getDeleteJobPropertyUrl(id,key),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteJobPropertyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobProperty>>, TError,{id: number;key: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJobProperty>>, TError,{id: number;key: string}, TContext> => {

const mutationKey = ['deleteJobProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJobProperty>>, {id: number;key: string}> = (props) => {
          const {id,key} = props ?? {};

          return  deleteJobProperty(id,key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJobProperty>>>

    export type DeleteJobPropertyMutationError = unknown

    export const useDeleteJobProperty = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobProperty>>, TError,{id: number;key: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteJobProperty>>,
        TError,
        {id: number;key: string},
        TContext
      > => {
      return useMutation(getDeleteJobPropertyMutationOptions(options), queryClient);
    }
    export type createJobFollowUpResponse200 = {
  data: void
  status: 200
}

export type createJobFollowUpResponseSuccess = (createJobFollowUpResponse200) & {
  headers: Headers;
};
;

export type createJobFollowUpResponse = (createJobFollowUpResponseSuccess)

export const getCreateJobFollowUpUrl = (id: number,) => {




  return `/api/jobs/${id}/follow-ups`
}

export const createJobFollowUp = async (id: number,
    createFollowUpTaskRequest: CreateFollowUpTaskRequest, options?: RequestInit): Promise<createJobFollowUpResponse> => {

  return apiClient<createJobFollowUpResponse>(getCreateJobFollowUpUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFollowUpTaskRequest)
  }
);}





export const getCreateJobFollowUpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobFollowUp>>, TError,{id: number;data: CreateFollowUpTaskRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createJobFollowUp>>, TError,{id: number;data: CreateFollowUpTaskRequest}, TContext> => {

const mutationKey = ['createJobFollowUp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJobFollowUp>>, {id: number;data: CreateFollowUpTaskRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  createJobFollowUp(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateJobFollowUpMutationResult = NonNullable<Awaited<ReturnType<typeof createJobFollowUp>>>
    export type CreateJobFollowUpMutationBody = CreateFollowUpTaskRequest
    export type CreateJobFollowUpMutationError = unknown

    export const useCreateJobFollowUp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobFollowUp>>, TError,{id: number;data: CreateFollowUpTaskRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createJobFollowUp>>,
        TError,
        {id: number;data: CreateFollowUpTaskRequest},
        TContext
      > => {
      return useMutation(getCreateJobFollowUpMutationOptions(options), queryClient);
    }
    export type setJobPriorityResponse200 = {
  data: void
  status: 200
}

export type setJobPriorityResponseSuccess = (setJobPriorityResponse200) & {
  headers: Headers;
};
;

export type setJobPriorityResponse = (setJobPriorityResponseSuccess)

export const getSetJobPriorityUrl = (id: number,) => {




  return `/api/jobs/${id}/priority`
}

export const setJobPriority = async (id: number,
    setJobPriorityRequest: SetJobPriorityRequest, options?: RequestInit): Promise<setJobPriorityResponse> => {

  return apiClient<setJobPriorityResponse>(getSetJobPriorityUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setJobPriorityRequest)
  }
);}




export const getSetJobPriorityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setJobPriority>>, TError,{id: number;data: SetJobPriorityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof setJobPriority>>, TError,{id: number;data: SetJobPriorityRequest}, TContext> => {

const mutationKey = ['setJobPriority'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setJobPriority>>, {id: number;data: SetJobPriorityRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  setJobPriority(id,data,requestOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type SetJobPriorityMutationResult = NonNullable<Awaited<ReturnType<typeof setJobPriority>>>
    export type SetJobPriorityMutationBody = SetJobPriorityRequest
    export type SetJobPriorityMutationError = unknown

    export const useSetJobPriority = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setJobPriority>>, TError,{id: number;data: SetJobPriorityRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setJobPriority>>,
        TError,
        {id: number;data: SetJobPriorityRequest},
        TContext
      > => {
      return useMutation(getSetJobPriorityMutationOptions(options), queryClient);
    }
