/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getDashboardSummaryResponseActiveApplicationCountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseLeadsByStatusItemCountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseApplicationsByStageItemCountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseFollowUpsDueItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseFollowUpsDueItemRelatedEntityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseOverdueFollowUpsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseOverdueFollowUpsItemRelatedEntityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseUpcomingInterviewsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseUpcomingInterviewsItemApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseUpcomingInterviewsItemDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseHighPriorityLeadsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseHighPriorityLeadsItemCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseHighPriorityLeadsItemSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getDashboardSummaryResponseHighPriorityLeadsItemSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getDashboardSummaryResponseHighPriorityLeadsItemFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseStaleApplicationsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseStaleApplicationsItemJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseStaleApplicationsItemResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseStaleApplicationsItemExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getDashboardSummaryResponseSearchDeadlineTwoDaysRemainingRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetDashboardSummaryResponse = zod.object({
  "activeApplicationCount": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseActiveApplicationCountRegExpTwo)]),
  "leadsByStatus": zod.array(zod.object({
  "status": zod.number(),
  "count": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseLeadsByStatusItemCountRegExpTwo)])
})),
  "applicationsByStage": zod.array(zod.object({
  "stage": zod.number(),
  "count": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseApplicationsByStageItemCountRegExpTwo)])
})),
  "followUpsDue": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseFollowUpsDueItemIdRegExpTwo)]),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "relatedEntityType": zod.number(),
  "relatedEntityId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseFollowUpsDueItemRelatedEntityIdRegExpTwo)]).nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "status": zod.number(),
  "priority": zod.number(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "overdueFollowUps": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseOverdueFollowUpsItemIdRegExpTwo)]),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "relatedEntityType": zod.number(),
  "relatedEntityId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseOverdueFollowUpsItemRelatedEntityIdRegExpTwo)]).nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "status": zod.number(),
  "priority": zod.number(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "upcomingInterviews": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseUpcomingInterviewsItemIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseUpcomingInterviewsItemApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseUpcomingInterviewsItemDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "highPriorityLeads": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseHighPriorityLeadsItemIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseHighPriorityLeadsItemCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', getDashboardSummaryResponseHighPriorityLeadsItemSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', getDashboardSummaryResponseHighPriorityLeadsItemSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseHighPriorityLeadsItemFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "staleApplications": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseStaleApplicationsItemIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseStaleApplicationsItemJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseStaleApplicationsItemResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', getDashboardSummaryResponseStaleApplicationsItemExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})),
  "searchDeadline": zod.union([zod.null(),zod.object({
  "deadlineUtc": zod.iso.datetime({"offset":true}),
  "daysRemaining": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseSearchDeadlineTwoDaysRemainingRegExpTwo)])
})])
})

