/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getDashboardSummaryResponseActiveJobsByStatusRegExpThree = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseFollowUpsDueTodayRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseOverdueFollowUpsRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseUpcomingActivitiesItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseUpcomingActivitiesItemActivityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseStaleJobsItemIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseOfferDeadlinesItemJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getDashboardSummaryResponseDaysUntilSearchDeadlineRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetDashboardSummaryResponse = zod.object({
  "activeJobsByStatus": zod.record(zod.string(), zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseActiveJobsByStatusRegExpThree)])),
  "followUpsDueToday": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseFollowUpsDueTodayRegExpTwo)]),
  "overdueFollowUps": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseOverdueFollowUpsRegExpTwo)]),
  "upcomingActivities": zod.array(zod.object({
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseUpcomingActivitiesItemJobIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "activityId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseUpcomingActivitiesItemActivityIdRegExpTwo)]),
  "activityLabel": zod.string(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true})
})),
  "staleJobs": zod.array(zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseStaleJobsItemIdRegExpTwo)]),
  "title": zod.string(),
  "companyName": zod.string(),
  "status": zod.enum(['Discovered', 'Interested', 'Applied', 'Interviewing', 'Offered', 'Rejected', 'Ghosted', 'Withdrawn', 'Archived']),
  "updatedAtUtc": zod.iso.datetime({"offset":true}),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable()
})),
  "offerDeadlines": zod.array(zod.object({
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseOfferDeadlinesItemJobIdRegExpTwo)]),
  "title": zod.string(),
  "companyName": zod.string(),
  "offerDeadlineAtUtc": zod.iso.datetime({"offset":true})
})),
  "daysUntilSearchDeadline": zod.union([zod.number(),zod.stringFormat('int32', getDashboardSummaryResponseDaysUntilSearchDeadlineRegExpTwo)]).nullable()
})

