/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getCompaniesResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetCompaniesResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getCompaniesResponseIdRegExpTwo)]),
  "name": zod.string(),
  "websiteUrl": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "companyType": zod.enum(['Unknown', 'Product', 'Outsourcing', 'Startup', 'Enterprise', 'Agency']),
  "marketType": zod.enum(['Unknown', 'Local', 'Remote', 'Hybrid', 'International']),
  "compensationFit": zod.enum(['Unknown', 'Low', 'Medium', 'High']),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const GetCompaniesResponse = zod.array(GetCompaniesResponseItem)

export const CreateCompanyBody = zod.object({
  "name": zod.string(),
  "websiteUrl": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "companyType": zod.enum(['Unknown', 'Product', 'Outsourcing', 'Startup', 'Enterprise', 'Agency']),
  "marketType": zod.enum(['Unknown', 'Local', 'Remote', 'Hybrid', 'International']),
  "compensationFit": zod.enum(['Unknown', 'Low', 'Medium', 'High']),
  "notes": zod.string().nullable()
})

export const createCompanyResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateCompanyResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createCompanyResponseIdRegExpTwo)]),
  "name": zod.string(),
  "websiteUrl": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "companyType": zod.enum(['Unknown', 'Product', 'Outsourcing', 'Startup', 'Enterprise', 'Agency']),
  "marketType": zod.enum(['Unknown', 'Local', 'Remote', 'Hybrid', 'International']),
  "compensationFit": zod.enum(['Unknown', 'Low', 'Medium', 'High']),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const GetCompanyParams = zod.object({
  "id": zod.number()
})

export const getCompanyResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetCompanyResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getCompanyResponseIdRegExpTwo)]),
  "name": zod.string(),
  "websiteUrl": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "companyType": zod.enum(['Unknown', 'Product', 'Outsourcing', 'Startup', 'Enterprise', 'Agency']),
  "marketType": zod.enum(['Unknown', 'Local', 'Remote', 'Hybrid', 'International']),
  "compensationFit": zod.enum(['Unknown', 'Low', 'Medium', 'High']),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const UpdateCompanyParams = zod.object({
  "id": zod.number()
})

export const UpdateCompanyBody = zod.object({
  "name": zod.string(),
  "websiteUrl": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "companyType": zod.enum(['Unknown', 'Product', 'Outsourcing', 'Startup', 'Enterprise', 'Agency']),
  "marketType": zod.enum(['Unknown', 'Local', 'Remote', 'Hybrid', 'International']),
  "compensationFit": zod.enum(['Unknown', 'Low', 'Medium', 'High']),
  "notes": zod.string().nullable()
})

export const updateCompanyResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateCompanyResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', updateCompanyResponseIdRegExpTwo)]),
  "name": zod.string(),
  "websiteUrl": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "country": zod.string().nullable(),
  "city": zod.string().nullable(),
  "companyType": zod.enum(['Unknown', 'Product', 'Outsourcing', 'Startup', 'Enterprise', 'Agency']),
  "marketType": zod.enum(['Unknown', 'Local', 'Remote', 'Hybrid', 'International']),
  "compensationFit": zod.enum(['Unknown', 'Low', 'Medium', 'High']),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const DeleteCompanyParams = zod.object({
  "id": zod.number()
})

export const DeleteCompanyResponse = zod.unknown()

