/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompanyDto,
  CreateCompanyRequest,
  HttpValidationProblemDetails,
  UpdateCompanyRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCompaniesResponse200 = {
  data: CompanyDto[]
  status: 200
}

export type getCompaniesResponseSuccess = (getCompaniesResponse200) & {
  headers: Headers;
};
;

export type getCompaniesResponse = (getCompaniesResponseSuccess)

export const getGetCompaniesUrl = () => {




  return `/api/companies`
}

export const getCompanies = async ( options?: RequestInit): Promise<getCompaniesResponse> => {

  return apiClient<getCompaniesResponse>(getGetCompaniesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompaniesQueryKey = () => {
    return [
    `/api/companies`
    ] as const;
    }


export const getGetCompaniesQueryOptions = <TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompaniesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanies>>> = ({ signal }) => getCompanies({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompaniesQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanies>>>
export type GetCompaniesQueryError = unknown


export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanies>>,
          TError,
          Awaited<ReturnType<typeof getCompanies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanies>>,
          TError,
          Awaited<ReturnType<typeof getCompanies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompaniesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createCompanyResponse201 = {
  data: CompanyDto
  status: 201
}

export type createCompanyResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createCompanyResponseSuccess = (createCompanyResponse201) & {
  headers: Headers;
};
export type createCompanyResponseError = (createCompanyResponse400) & {
  headers: Headers;
};

export type createCompanyResponse = (createCompanyResponseSuccess | createCompanyResponseError)

export const getCreateCompanyUrl = () => {




  return `/api/companies`
}

export const createCompany = async (createCompanyRequest: CreateCompanyRequest, options?: RequestInit): Promise<createCompanyResponse> => {

  return apiClient<createCompanyResponse>(getCreateCompanyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCompanyRequest)
  }
);}




export const getCreateCompanyMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompany>>, TError,{data: CreateCompanyRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createCompany>>, TError,{data: CreateCompanyRequest}, TContext> => {

const mutationKey = ['createCompany'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCompany>>, {data: CreateCompanyRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCompany(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof createCompany>>>
    export type CreateCompanyMutationBody = CreateCompanyRequest
    export type CreateCompanyMutationError = HttpValidationProblemDetails

    export const useCreateCompany = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompany>>, TError,{data: CreateCompanyRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCompany>>,
        TError,
        {data: CreateCompanyRequest},
        TContext
      > => {
      return useMutation(getCreateCompanyMutationOptions(options), queryClient);
    }
    export type getCompanyResponse200 = {
  data: CompanyDto
  status: 200
}

export type getCompanyResponse404 = {
  data: void
  status: 404
}

export type getCompanyResponseSuccess = (getCompanyResponse200) & {
  headers: Headers;
};
export type getCompanyResponseError = (getCompanyResponse404) & {
  headers: Headers;
};

export type getCompanyResponse = (getCompanyResponseSuccess | getCompanyResponseError)

export const getGetCompanyUrl = (id: number,) => {




  return `/api/companies/${id}`
}

export const getCompany = async (id: number, options?: RequestInit): Promise<getCompanyResponse> => {

  return apiClient<getCompanyResponse>(getGetCompanyUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompanyQueryKey = (id: number,) => {
    return [
    `/api/companies/${id}`
    ] as const;
    }


export const getGetCompanyQueryOptions = <TData = Awaited<ReturnType<typeof getCompany>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompanyQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompany>>> = ({ signal }) => getCompany(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompanyQueryResult = NonNullable<Awaited<ReturnType<typeof getCompany>>>
export type GetCompanyQueryError = void


export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompany>>,
          TError,
          Awaited<ReturnType<typeof getCompany>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompany>>,
          TError,
          Awaited<ReturnType<typeof getCompany>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompanyQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateCompanyResponse200 = {
  data: CompanyDto
  status: 200
}

export type updateCompanyResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateCompanyResponse404 = {
  data: void
  status: 404
}

export type updateCompanyResponseSuccess = (updateCompanyResponse200) & {
  headers: Headers;
};
export type updateCompanyResponseError = (updateCompanyResponse400 | updateCompanyResponse404) & {
  headers: Headers;
};

export type updateCompanyResponse = (updateCompanyResponseSuccess | updateCompanyResponseError)

export const getUpdateCompanyUrl = (id: number,) => {




  return `/api/companies/${id}`
}

export const updateCompany = async (id: number,
    updateCompanyRequest: UpdateCompanyRequest, options?: RequestInit): Promise<updateCompanyResponse> => {

  return apiClient<updateCompanyResponse>(getUpdateCompanyUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCompanyRequest)
  }
);}




export const getUpdateCompanyMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCompany>>, TError,{id: number;data: UpdateCompanyRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCompany>>, TError,{id: number;data: UpdateCompanyRequest}, TContext> => {

const mutationKey = ['updateCompany'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCompany>>, {id: number;data: UpdateCompanyRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCompany(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof updateCompany>>>
    export type UpdateCompanyMutationBody = UpdateCompanyRequest
    export type UpdateCompanyMutationError = HttpValidationProblemDetails | void

    export const useUpdateCompany = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCompany>>, TError,{id: number;data: UpdateCompanyRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCompany>>,
        TError,
        {id: number;data: UpdateCompanyRequest},
        TContext
      > => {
      return useMutation(getUpdateCompanyMutationOptions(options), queryClient);
    }
    export type deleteCompanyResponse204 = {
  data: void
  status: 204
}

export type deleteCompanyResponse404 = {
  data: void
  status: 404
}

export type deleteCompanyResponseSuccess = (deleteCompanyResponse204) & {
  headers: Headers;
};
export type deleteCompanyResponseError = (deleteCompanyResponse404) & {
  headers: Headers;
};

export type deleteCompanyResponse = (deleteCompanyResponseSuccess | deleteCompanyResponseError)

export const getDeleteCompanyUrl = (id: number,) => {




  return `/api/companies/${id}`
}

export const deleteCompany = async (id: number, options?: RequestInit): Promise<deleteCompanyResponse> => {

  return apiClient<deleteCompanyResponse>(getDeleteCompanyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCompanyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCompany'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompany>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCompany(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompany>>>

    export type DeleteCompanyMutationError = void

    export const useDeleteCompany = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompany>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCompanyMutationOptions(options), queryClient);
    }
