// <auto-generated />
using System;
using CareerOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CareerOpsDbContext))]
    [Migration("20260626060223_DomainV2")]
    partial class DomainV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerOps.Domain.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<int>("CompanyType")
                        .HasColumnType("integer")
                        .HasColumnName("company_type");

                    b.Property<int>("CompensationFit")
                        .HasColumnType("integer")
                        .HasColumnName("compensation_fit");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("linked_in_url");

                    b.Property<int>("MarketType")
                        .HasColumnType("integer")
                        .HasColumnName("market_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_companies_name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.FollowUpTasks.FollowUpTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<int?>("JobActivityId")
                        .HasColumnType("integer")
                        .HasColumnName("job_activity_id");

                    b.Property<int?>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_follow_up_tasks");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("ix_follow_up_tasks_due_at_utc");

                    b.HasIndex("JobActivityId")
                        .HasDatabaseName("ix_follow_up_tasks_job_activity_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_follow_up_tasks_job_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_follow_up_tasks_status");

                    b.ToTable("follow_up_tasks", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("CoverLetterNotes")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter_notes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeadlineAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at_utc");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer")
                        .HasColumnName("employment_type");

                    b.Property<int?>("FitScore")
                        .HasColumnType("integer")
                        .HasColumnName("fit_score");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<DateTime?>("LastContactedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_contacted_at_utc");

                    b.Property<string>("LocationText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_text");

                    b.Property<DateTime?>("NextActionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OfferCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("offer_currency");

                    b.Property<DateTime?>("OfferDeadlineAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_deadline_at_utc");

                    b.Property<string>("OfferNotes")
                        .HasColumnType("text")
                        .HasColumnName("offer_notes");

                    b.Property<decimal?>("OfferSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("offer_salary");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("RemoteMode")
                        .HasColumnType("integer")
                        .HasColumnName("remote_mode");

                    b.Property<string>("ResumeAngle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resume_angle");

                    b.Property<string>("ResumeLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resume_label");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("salary_currency");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_min");

                    b.Property<int>("SalaryPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("salary_period");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_jobs_company_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactRole")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_role");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("meeting_url");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("PrepNotes")
                        .HasColumnType("text")
                        .HasColumnName("prep_notes");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_job_activities");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_activities_job_id");

                    b.ToTable("job_activities", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_job_attachments");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_attachments_job_id");

                    b.ToTable("job_attachments", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_job_properties");

                    b.HasIndex("JobId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_job_properties_job_id_key");

                    b.ToTable("job_properties", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Actor")
                        .HasColumnType("integer")
                        .HasColumnName("actor");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_job_transitions");

                    b.HasIndex("ChangedAtUtc")
                        .HasDatabaseName("ix_job_transitions_changed_at_utc");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_transitions_job_id");

                    b.ToTable("job_transitions", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CareerSummary")
                        .HasColumnType("text")
                        .HasColumnName("career_summary");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text")
                        .HasColumnName("current_location");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_url");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text")
                        .HasColumnName("linked_in_url");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("text")
                        .HasColumnName("portfolio_url");

                    b.Property<string>("PreferredTechStack")
                        .HasColumnType("text")
                        .HasColumnName("preferred_tech_stack");

                    b.Property<DateTime?>("SearchDeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("search_deadline_utc");

                    b.Property<string>("TargetRoles")
                        .HasColumnType("text")
                        .HasColumnName("target_roles");

                    b.Property<string>("TargetSalaryCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("target_salary_currency");

                    b.Property<decimal?>("TargetSalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_salary_min");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("CareerOps.Domain.FollowUpTasks.FollowUpTask", b =>
                {
                    b.HasOne("CareerOps.Domain.Jobs.JobActivity", "JobActivity")
                        .WithMany("FollowUps")
                        .HasForeignKey("JobActivityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_follow_up_tasks_job_activities_job_activity_id");

                    b.HasOne("CareerOps.Domain.Jobs.Job", "Job")
                        .WithMany("FollowUps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_follow_up_tasks_jobs_job_id");

                    b.Navigation("Job");

                    b.Navigation("JobActivity");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.Job", b =>
                {
                    b.HasOne("CareerOps.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobActivity", b =>
                {
                    b.HasOne("CareerOps.Domain.Jobs.Job", "Job")
                        .WithMany("Activities")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_activities_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobAttachment", b =>
                {
                    b.HasOne("CareerOps.Domain.Jobs.Job", "Job")
                        .WithMany("Attachments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_attachments_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobProperty", b =>
                {
                    b.HasOne("CareerOps.Domain.Jobs.Job", "Job")
                        .WithMany("Properties")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_properties_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobTransition", b =>
                {
                    b.HasOne("CareerOps.Domain.Jobs.Job", "Job")
                        .WithMany("Transitions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_transitions_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Attachments");

                    b.Navigation("FollowUps");

                    b.Navigation("Properties");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("CareerOps.Domain.Jobs.JobActivity", b =>
                {
                    b.Navigation("FollowUps");
                });
#pragma warning restore 612, 618
        }
    }
}
