/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApplicationDto,
  ChangeStageRequest,
  ConvertToApplicationRequest,
  HttpValidationProblemDetails,
  MarkRejectedRequest,
  UpdateApplicationRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type convertToApplicationResponse201 = {
  data: ApplicationDto
  status: 201
}

export type convertToApplicationResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type convertToApplicationResponse404 = {
  data: void
  status: 404
}

export type convertToApplicationResponse409 = {
  data: string
  status: 409
}

export type convertToApplicationResponseSuccess = (convertToApplicationResponse201) & {
  headers: Headers;
};
export type convertToApplicationResponseError = (convertToApplicationResponse400 | convertToApplicationResponse404 | convertToApplicationResponse409) & {
  headers: Headers;
};

export type convertToApplicationResponse = (convertToApplicationResponseSuccess | convertToApplicationResponseError)

export const getConvertToApplicationUrl = (id: number,) => {




  return `/api/job-leads/${id}/convert-to-application`
}

export const convertToApplication = async (id: number,
    convertToApplicationRequest: ConvertToApplicationRequest, options?: RequestInit): Promise<convertToApplicationResponse> => {

  return apiClient<convertToApplicationResponse>(getConvertToApplicationUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(convertToApplicationRequest)
  }
);}




export const getConvertToApplicationMutationOptions = <TError = HttpValidationProblemDetails | void | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof convertToApplication>>, TError,{id: number;data: ConvertToApplicationRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof convertToApplication>>, TError,{id: number;data: ConvertToApplicationRequest}, TContext> => {

const mutationKey = ['convertToApplication'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof convertToApplication>>, {id: number;data: ConvertToApplicationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  convertToApplication(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConvertToApplicationMutationResult = NonNullable<Awaited<ReturnType<typeof convertToApplication>>>
    export type ConvertToApplicationMutationBody = ConvertToApplicationRequest
    export type ConvertToApplicationMutationError = HttpValidationProblemDetails | void | string

    export const useConvertToApplication = <TError = HttpValidationProblemDetails | void | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof convertToApplication>>, TError,{id: number;data: ConvertToApplicationRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof convertToApplication>>,
        TError,
        {id: number;data: ConvertToApplicationRequest},
        TContext
      > => {
      return useMutation(getConvertToApplicationMutationOptions(options), queryClient);
    }
    export type getApplicationsResponse200 = {
  data: ApplicationDto[]
  status: 200
}

export type getApplicationsResponseSuccess = (getApplicationsResponse200) & {
  headers: Headers;
};
;

export type getApplicationsResponse = (getApplicationsResponseSuccess)

export const getGetApplicationsUrl = () => {




  return `/api/applications`
}

export const getApplications = async ( options?: RequestInit): Promise<getApplicationsResponse> => {

  return apiClient<getApplicationsResponse>(getGetApplicationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApplicationsQueryKey = () => {
    return [
    `/api/applications`
    ] as const;
    }


export const getGetApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof getApplications>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplications>>> = ({ signal }) => getApplications({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApplications>>>
export type GetApplicationsQueryError = unknown


export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplications>>,
          TError,
          Awaited<ReturnType<typeof getApplications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplications>>,
          TError,
          Awaited<ReturnType<typeof getApplications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApplicationResponse200 = {
  data: ApplicationDto
  status: 200
}

export type getApplicationResponse404 = {
  data: void
  status: 404
}

export type getApplicationResponseSuccess = (getApplicationResponse200) & {
  headers: Headers;
};
export type getApplicationResponseError = (getApplicationResponse404) & {
  headers: Headers;
};

export type getApplicationResponse = (getApplicationResponseSuccess | getApplicationResponseError)

export const getGetApplicationUrl = (id: number,) => {




  return `/api/applications/${id}`
}

export const getApplication = async (id: number, options?: RequestInit): Promise<getApplicationResponse> => {

  return apiClient<getApplicationResponse>(getGetApplicationUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApplicationQueryKey = (id: number,) => {
    return [
    `/api/applications/${id}`
    ] as const;
    }


export const getGetApplicationQueryOptions = <TData = Awaited<ReturnType<typeof getApplication>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplication>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplication>>> = ({ signal }) => getApplication(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplication>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationQueryResult = NonNullable<Awaited<ReturnType<typeof getApplication>>>
export type GetApplicationQueryError = void


export function useGetApplication<TData = Awaited<ReturnType<typeof getApplication>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplication>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplication>>,
          TError,
          Awaited<ReturnType<typeof getApplication>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplication<TData = Awaited<ReturnType<typeof getApplication>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplication>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplication>>,
          TError,
          Awaited<ReturnType<typeof getApplication>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplication<TData = Awaited<ReturnType<typeof getApplication>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplication>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApplication<TData = Awaited<ReturnType<typeof getApplication>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplication>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateApplicationResponse200 = {
  data: ApplicationDto
  status: 200
}

export type updateApplicationResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateApplicationResponse404 = {
  data: void
  status: 404
}

export type updateApplicationResponseSuccess = (updateApplicationResponse200) & {
  headers: Headers;
};
export type updateApplicationResponseError = (updateApplicationResponse400 | updateApplicationResponse404) & {
  headers: Headers;
};

export type updateApplicationResponse = (updateApplicationResponseSuccess | updateApplicationResponseError)

export const getUpdateApplicationUrl = (id: number,) => {




  return `/api/applications/${id}`
}

export const updateApplication = async (id: number,
    updateApplicationRequest: UpdateApplicationRequest, options?: RequestInit): Promise<updateApplicationResponse> => {

  return apiClient<updateApplicationResponse>(getUpdateApplicationUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateApplicationRequest)
  }
);}




export const getUpdateApplicationMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApplication>>, TError,{id: number;data: UpdateApplicationRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateApplication>>, TError,{id: number;data: UpdateApplicationRequest}, TContext> => {

const mutationKey = ['updateApplication'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateApplication>>, {id: number;data: UpdateApplicationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateApplication(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateApplicationMutationResult = NonNullable<Awaited<ReturnType<typeof updateApplication>>>
    export type UpdateApplicationMutationBody = UpdateApplicationRequest
    export type UpdateApplicationMutationError = HttpValidationProblemDetails | void

    export const useUpdateApplication = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApplication>>, TError,{id: number;data: UpdateApplicationRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateApplication>>,
        TError,
        {id: number;data: UpdateApplicationRequest},
        TContext
      > => {
      return useMutation(getUpdateApplicationMutationOptions(options), queryClient);
    }
    export type deleteApplicationResponse204 = {
  data: void
  status: 204
}

export type deleteApplicationResponse404 = {
  data: void
  status: 404
}

export type deleteApplicationResponseSuccess = (deleteApplicationResponse204) & {
  headers: Headers;
};
export type deleteApplicationResponseError = (deleteApplicationResponse404) & {
  headers: Headers;
};

export type deleteApplicationResponse = (deleteApplicationResponseSuccess | deleteApplicationResponseError)

export const getDeleteApplicationUrl = (id: number,) => {




  return `/api/applications/${id}`
}

export const deleteApplication = async (id: number, options?: RequestInit): Promise<deleteApplicationResponse> => {

  return apiClient<deleteApplicationResponse>(getDeleteApplicationUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApplicationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApplication>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApplication>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApplication'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApplication>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApplication(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApplicationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApplication>>>

    export type DeleteApplicationMutationError = void

    export const useDeleteApplication = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApplication>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApplication>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApplicationMutationOptions(options), queryClient);
    }
    export type changeApplicationStageResponse200 = {
  data: ApplicationDto
  status: 200
}

export type changeApplicationStageResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type changeApplicationStageResponse404 = {
  data: void
  status: 404
}

export type changeApplicationStageResponseSuccess = (changeApplicationStageResponse200) & {
  headers: Headers;
};
export type changeApplicationStageResponseError = (changeApplicationStageResponse400 | changeApplicationStageResponse404) & {
  headers: Headers;
};

export type changeApplicationStageResponse = (changeApplicationStageResponseSuccess | changeApplicationStageResponseError)

export const getChangeApplicationStageUrl = (id: number,) => {




  return `/api/applications/${id}/change-stage`
}

export const changeApplicationStage = async (id: number,
    changeStageRequest: ChangeStageRequest, options?: RequestInit): Promise<changeApplicationStageResponse> => {

  return apiClient<changeApplicationStageResponse>(getChangeApplicationStageUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(changeStageRequest)
  }
);}




export const getChangeApplicationStageMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeApplicationStage>>, TError,{id: number;data: ChangeStageRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof changeApplicationStage>>, TError,{id: number;data: ChangeStageRequest}, TContext> => {

const mutationKey = ['changeApplicationStage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeApplicationStage>>, {id: number;data: ChangeStageRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  changeApplicationStage(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChangeApplicationStageMutationResult = NonNullable<Awaited<ReturnType<typeof changeApplicationStage>>>
    export type ChangeApplicationStageMutationBody = ChangeStageRequest
    export type ChangeApplicationStageMutationError = HttpValidationProblemDetails | void

    export const useChangeApplicationStage = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeApplicationStage>>, TError,{id: number;data: ChangeStageRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeApplicationStage>>,
        TError,
        {id: number;data: ChangeStageRequest},
        TContext
      > => {
      return useMutation(getChangeApplicationStageMutationOptions(options), queryClient);
    }
    export type markApplicationRejectedResponse200 = {
  data: ApplicationDto
  status: 200
}

export type markApplicationRejectedResponse404 = {
  data: void
  status: 404
}

export type markApplicationRejectedResponseSuccess = (markApplicationRejectedResponse200) & {
  headers: Headers;
};
export type markApplicationRejectedResponseError = (markApplicationRejectedResponse404) & {
  headers: Headers;
};

export type markApplicationRejectedResponse = (markApplicationRejectedResponseSuccess | markApplicationRejectedResponseError)

export const getMarkApplicationRejectedUrl = (id: number,) => {




  return `/api/applications/${id}/mark-rejected`
}

export const markApplicationRejected = async (id: number,
    markRejectedRequest: MarkRejectedRequest, options?: RequestInit): Promise<markApplicationRejectedResponse> => {

  return apiClient<markApplicationRejectedResponse>(getMarkApplicationRejectedUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(markRejectedRequest)
  }
);}




export const getMarkApplicationRejectedMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markApplicationRejected>>, TError,{id: number;data: MarkRejectedRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof markApplicationRejected>>, TError,{id: number;data: MarkRejectedRequest}, TContext> => {

const mutationKey = ['markApplicationRejected'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markApplicationRejected>>, {id: number;data: MarkRejectedRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  markApplicationRejected(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkApplicationRejectedMutationResult = NonNullable<Awaited<ReturnType<typeof markApplicationRejected>>>
    export type MarkApplicationRejectedMutationBody = MarkRejectedRequest
    export type MarkApplicationRejectedMutationError = void

    export const useMarkApplicationRejected = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markApplicationRejected>>, TError,{id: number;data: MarkRejectedRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markApplicationRejected>>,
        TError,
        {id: number;data: MarkRejectedRequest},
        TContext
      > => {
      return useMutation(getMarkApplicationRejectedMutationOptions(options), queryClient);
    }
    export type markApplicationOfferResponse200 = {
  data: ApplicationDto
  status: 200
}

export type markApplicationOfferResponse404 = {
  data: void
  status: 404
}

export type markApplicationOfferResponseSuccess = (markApplicationOfferResponse200) & {
  headers: Headers;
};
export type markApplicationOfferResponseError = (markApplicationOfferResponse404) & {
  headers: Headers;
};

export type markApplicationOfferResponse = (markApplicationOfferResponseSuccess | markApplicationOfferResponseError)

export const getMarkApplicationOfferUrl = (id: number,) => {




  return `/api/applications/${id}/mark-offer`
}

export const markApplicationOffer = async (id: number, options?: RequestInit): Promise<markApplicationOfferResponse> => {

  return apiClient<markApplicationOfferResponse>(getMarkApplicationOfferUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getMarkApplicationOfferMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markApplicationOffer>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof markApplicationOffer>>, TError,{id: number}, TContext> => {

const mutationKey = ['markApplicationOffer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markApplicationOffer>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  markApplicationOffer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkApplicationOfferMutationResult = NonNullable<Awaited<ReturnType<typeof markApplicationOffer>>>

    export type MarkApplicationOfferMutationError = void

    export const useMarkApplicationOffer = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markApplicationOffer>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markApplicationOffer>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getMarkApplicationOfferMutationOptions(options), queryClient);
    }
    export type markApplicationGhostedResponse200 = {
  data: ApplicationDto
  status: 200
}

export type markApplicationGhostedResponse404 = {
  data: void
  status: 404
}

export type markApplicationGhostedResponseSuccess = (markApplicationGhostedResponse200) & {
  headers: Headers;
};
export type markApplicationGhostedResponseError = (markApplicationGhostedResponse404) & {
  headers: Headers;
};

export type markApplicationGhostedResponse = (markApplicationGhostedResponseSuccess | markApplicationGhostedResponseError)

export const getMarkApplicationGhostedUrl = (id: number,) => {




  return `/api/applications/${id}/mark-ghosted`
}

export const markApplicationGhosted = async (id: number, options?: RequestInit): Promise<markApplicationGhostedResponse> => {

  return apiClient<markApplicationGhostedResponse>(getMarkApplicationGhostedUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getMarkApplicationGhostedMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markApplicationGhosted>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof markApplicationGhosted>>, TError,{id: number}, TContext> => {

const mutationKey = ['markApplicationGhosted'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markApplicationGhosted>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  markApplicationGhosted(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkApplicationGhostedMutationResult = NonNullable<Awaited<ReturnType<typeof markApplicationGhosted>>>

    export type MarkApplicationGhostedMutationError = void

    export const useMarkApplicationGhosted = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markApplicationGhosted>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markApplicationGhosted>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getMarkApplicationGhostedMutationOptions(options), queryClient);
    }
