/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const ConvertToApplicationParams = zod.object({
  "id": zod.number()
})

export const convertToApplicationBodyResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const ConvertToApplicationBody = zod.object({
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', convertToApplicationBodyResumeVariantIdRegExpTwo)]),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable()
})

export const convertToApplicationResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const convertToApplicationResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const convertToApplicationResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const convertToApplicationResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const ConvertToApplicationResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', convertToApplicationResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', convertToApplicationResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', convertToApplicationResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', convertToApplicationResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const getApplicationsResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApplicationsResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApplicationsResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApplicationsResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const GetApplicationsResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getApplicationsResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', getApplicationsResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', getApplicationsResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', getApplicationsResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const GetApplicationsResponse = zod.array(GetApplicationsResponseItem)

export const GetApplicationParams = zod.object({
  "id": zod.number()
})

export const getApplicationResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApplicationResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApplicationResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApplicationResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const GetApplicationResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getApplicationResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', getApplicationResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', getApplicationResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', getApplicationResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const UpdateApplicationParams = zod.object({
  "id": zod.number()
})

export const updateApplicationBodyResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateApplicationBodyExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const UpdateApplicationBody = zod.object({
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', updateApplicationBodyResumeVariantIdRegExpTwo)]),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', updateApplicationBodyExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable()
})

export const updateApplicationResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateApplicationResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateApplicationResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateApplicationResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const UpdateApplicationResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', updateApplicationResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', updateApplicationResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', updateApplicationResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', updateApplicationResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const DeleteApplicationParams = zod.object({
  "id": zod.number()
})

export const DeleteApplicationResponse = zod.void()

export const ChangeApplicationStageParams = zod.object({
  "id": zod.number()
})

export const ChangeApplicationStageBody = zod.object({
  "stage": zod.number()
})

export const changeApplicationStageResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const changeApplicationStageResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const changeApplicationStageResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const changeApplicationStageResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const ChangeApplicationStageResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', changeApplicationStageResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', changeApplicationStageResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', changeApplicationStageResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', changeApplicationStageResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const MarkApplicationRejectedParams = zod.object({
  "id": zod.number()
})

export const MarkApplicationRejectedBody = zod.object({
  "rejectionReason": zod.string().nullable()
})

export const markApplicationRejectedResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationRejectedResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationRejectedResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationRejectedResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const MarkApplicationRejectedResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', markApplicationRejectedResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', markApplicationRejectedResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', markApplicationRejectedResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', markApplicationRejectedResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const MarkApplicationOfferParams = zod.object({
  "id": zod.number()
})

export const markApplicationOfferResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationOfferResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationOfferResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationOfferResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const MarkApplicationOfferResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', markApplicationOfferResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', markApplicationOfferResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', markApplicationOfferResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', markApplicationOfferResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const MarkApplicationGhostedParams = zod.object({
  "id": zod.number()
})

export const markApplicationGhostedResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationGhostedResponseJobLeadIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationGhostedResponseResumeVariantIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markApplicationGhostedResponseExpectedSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const MarkApplicationGhostedResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', markApplicationGhostedResponseIdRegExpTwo)]),
  "jobLeadId": zod.union([zod.number(),zod.stringFormat('int32', markApplicationGhostedResponseJobLeadIdRegExpTwo)]),
  "jobTitle": zod.string(),
  "companyName": zod.string(),
  "resumeVariantId": zod.union([zod.number(),zod.stringFormat('int32', markApplicationGhostedResponseResumeVariantIdRegExpTwo)]),
  "resumeVariantName": zod.string(),
  "appliedAtUtc": zod.iso.datetime({"offset":true}),
  "currentStage": zod.number(),
  "status": zod.number(),
  "expectedSalary": zod.union([zod.number(),zod.stringFormat('double', markApplicationGhostedResponseExpectedSalaryRegExpTwo)]).nullable(),
  "expectedSalaryCurrency": zod.string().nullable(),
  "noticePeriod": zod.string().nullable(),
  "nextStep": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "rejectionReason": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

