/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getUserProfileResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getUserProfileResponseTargetSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const GetUserProfileResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getUserProfileResponseIdRegExpTwo)]),
  "fullName": zod.string(),
  "email": zod.string().nullable(),
  "phone": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "gitHubUrl": zod.string().nullable(),
  "portfolioUrl": zod.string().nullable(),
  "currentLocation": zod.string().nullable(),
  "targetRoles": zod.string().nullable(),
  "targetSalaryMin": zod.union([zod.number(),zod.stringFormat('double', getUserProfileResponseTargetSalaryMinRegExpTwo)]).nullable(),
  "targetSalaryCurrency": zod.string().nullable(),
  "searchDeadlineUtc": zod.iso.datetime({"offset":true}).nullable(),
  "preferredTechStack": zod.string().nullable(),
  "careerSummary": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const updateUserProfileBodyTargetSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const UpdateUserProfileBody = zod.object({
  "fullName": zod.string(),
  "email": zod.string().nullable(),
  "phone": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "gitHubUrl": zod.string().nullable(),
  "portfolioUrl": zod.string().nullable(),
  "currentLocation": zod.string().nullable(),
  "targetRoles": zod.string().nullable(),
  "targetSalaryMin": zod.union([zod.number(),zod.stringFormat('double', updateUserProfileBodyTargetSalaryMinRegExpTwo)]).nullable(),
  "targetSalaryCurrency": zod.string().nullable(),
  "searchDeadlineUtc": zod.iso.datetime({"offset":true}).nullable(),
  "preferredTechStack": zod.string().nullable(),
  "careerSummary": zod.string().nullable()
})

export const updateUserProfileResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateUserProfileResponseTargetSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const UpdateUserProfileResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', updateUserProfileResponseIdRegExpTwo)]),
  "fullName": zod.string(),
  "email": zod.string().nullable(),
  "phone": zod.string().nullable(),
  "linkedInUrl": zod.string().nullable(),
  "gitHubUrl": zod.string().nullable(),
  "portfolioUrl": zod.string().nullable(),
  "currentLocation": zod.string().nullable(),
  "targetRoles": zod.string().nullable(),
  "targetSalaryMin": zod.union([zod.number(),zod.stringFormat('double', updateUserProfileResponseTargetSalaryMinRegExpTwo)]).nullable(),
  "targetSalaryCurrency": zod.string().nullable(),
  "searchDeadlineUtc": zod.iso.datetime({"offset":true}).nullable(),
  "preferredTechStack": zod.string().nullable(),
  "careerSummary": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

