/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getJobLeadsResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobLeadsResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobLeadsResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobLeadsResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobLeadsResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetJobLeadsResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobLeadsResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', getJobLeadsResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', getJobLeadsResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', getJobLeadsResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', getJobLeadsResponseFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const GetJobLeadsResponse = zod.array(GetJobLeadsResponseItem)

export const createJobLeadBodyCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobLeadBodySalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobLeadBodySalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobLeadBodyFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateJobLeadBody = zod.object({
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', createJobLeadBodyCompanyIdRegExpTwo)]).nullable(),
  "newCompanyName": zod.string().nullable(),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', createJobLeadBodySalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', createJobLeadBodySalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', createJobLeadBodyFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable()
})

export const createJobLeadResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobLeadResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createJobLeadResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobLeadResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const createJobLeadResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateJobLeadResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createJobLeadResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', createJobLeadResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', createJobLeadResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', createJobLeadResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', createJobLeadResponseFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const GetJobLeadParams = zod.object({
  "id": zod.number()
})

export const getJobLeadResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobLeadResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getJobLeadResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobLeadResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const getJobLeadResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetJobLeadResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getJobLeadResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', getJobLeadResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', getJobLeadResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', getJobLeadResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', getJobLeadResponseFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const UpdateJobLeadParams = zod.object({
  "id": zod.number()
})

export const updateJobLeadBodyCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateJobLeadBodySalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const updateJobLeadBodySalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const updateJobLeadBodyFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateJobLeadBody = zod.object({
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', updateJobLeadBodyCompanyIdRegExpTwo)]),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', updateJobLeadBodySalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', updateJobLeadBodySalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', updateJobLeadBodyFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable()
})

export const updateJobLeadResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateJobLeadResponseCompanyIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateJobLeadResponseSalaryMinRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const updateJobLeadResponseSalaryMaxRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const updateJobLeadResponseFitScoreRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateJobLeadResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', updateJobLeadResponseIdRegExpTwo)]),
  "companyId": zod.union([zod.number(),zod.stringFormat('int32', updateJobLeadResponseCompanyIdRegExpTwo)]),
  "companyName": zod.string(),
  "title": zod.string(),
  "source": zod.number(),
  "sourceUrl": zod.string().nullable(),
  "jobDescription": zod.string().nullable(),
  "location": zod.string().nullable(),
  "remoteMode": zod.number(),
  "employmentType": zod.number(),
  "salaryMin": zod.union([zod.number(),zod.stringFormat('double', updateJobLeadResponseSalaryMinRegExpTwo)]).nullable(),
  "salaryMax": zod.union([zod.number(),zod.stringFormat('double', updateJobLeadResponseSalaryMaxRegExpTwo)]).nullable(),
  "salaryCurrency": zod.string().nullable(),
  "salaryPeriod": zod.number(),
  "priority": zod.number(),
  "status": zod.number(),
  "fitScore": zod.union([zod.number(),zod.stringFormat('int32', updateJobLeadResponseFitScoreRegExpTwo)]).nullable(),
  "aiSummary": zod.string().nullable(),
  "missingKeywords": zod.string().nullable(),
  "suggestedResumeAngle": zod.string().nullable(),
  "nextActionAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "deadlineAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "notes": zod.string().nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const DeleteJobLeadParams = zod.object({
  "id": zod.number()
})

export const DeleteJobLeadResponse = zod.void()

