/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateJobLeadRequest,
  HttpValidationProblemDetails,
  JobLeadDto,
  UpdateJobLeadRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getJobLeadsResponse200 = {
  data: JobLeadDto[]
  status: 200
}

export type getJobLeadsResponseSuccess = (getJobLeadsResponse200) & {
  headers: Headers;
};
;

export type getJobLeadsResponse = (getJobLeadsResponseSuccess)

export const getGetJobLeadsUrl = () => {




  return `/api/job-leads`
}

export const getJobLeads = async ( options?: RequestInit): Promise<getJobLeadsResponse> => {

  return apiClient<getJobLeadsResponse>(getGetJobLeadsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobLeadsQueryKey = () => {
    return [
    `/api/job-leads`
    ] as const;
    }


export const getGetJobLeadsQueryOptions = <TData = Awaited<ReturnType<typeof getJobLeads>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLeads>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobLeadsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobLeads>>> = ({ signal }) => getJobLeads({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobLeads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobLeadsQueryResult = NonNullable<Awaited<ReturnType<typeof getJobLeads>>>
export type GetJobLeadsQueryError = unknown


export function useGetJobLeads<TData = Awaited<ReturnType<typeof getJobLeads>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLeads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobLeads>>,
          TError,
          Awaited<ReturnType<typeof getJobLeads>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobLeads<TData = Awaited<ReturnType<typeof getJobLeads>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLeads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobLeads>>,
          TError,
          Awaited<ReturnType<typeof getJobLeads>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobLeads<TData = Awaited<ReturnType<typeof getJobLeads>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLeads>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetJobLeads<TData = Awaited<ReturnType<typeof getJobLeads>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLeads>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobLeadsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createJobLeadResponse201 = {
  data: JobLeadDto
  status: 201
}

export type createJobLeadResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createJobLeadResponseSuccess = (createJobLeadResponse201) & {
  headers: Headers;
};
export type createJobLeadResponseError = (createJobLeadResponse400) & {
  headers: Headers;
};

export type createJobLeadResponse = (createJobLeadResponseSuccess | createJobLeadResponseError)

export const getCreateJobLeadUrl = () => {




  return `/api/job-leads`
}

export const createJobLead = async (createJobLeadRequest: CreateJobLeadRequest, options?: RequestInit): Promise<createJobLeadResponse> => {

  return apiClient<createJobLeadResponse>(getCreateJobLeadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createJobLeadRequest)
  }
);}




export const getCreateJobLeadMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobLead>>, TError,{data: CreateJobLeadRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createJobLead>>, TError,{data: CreateJobLeadRequest}, TContext> => {

const mutationKey = ['createJobLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJobLead>>, {data: CreateJobLeadRequest}> = (props) => {
          const {data} = props ?? {};

          return  createJobLead(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateJobLeadMutationResult = NonNullable<Awaited<ReturnType<typeof createJobLead>>>
    export type CreateJobLeadMutationBody = CreateJobLeadRequest
    export type CreateJobLeadMutationError = HttpValidationProblemDetails

    export const useCreateJobLead = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobLead>>, TError,{data: CreateJobLeadRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createJobLead>>,
        TError,
        {data: CreateJobLeadRequest},
        TContext
      > => {
      return useMutation(getCreateJobLeadMutationOptions(options), queryClient);
    }
    export type getJobLeadResponse200 = {
  data: JobLeadDto
  status: 200
}

export type getJobLeadResponse404 = {
  data: void
  status: 404
}

export type getJobLeadResponseSuccess = (getJobLeadResponse200) & {
  headers: Headers;
};
export type getJobLeadResponseError = (getJobLeadResponse404) & {
  headers: Headers;
};

export type getJobLeadResponse = (getJobLeadResponseSuccess | getJobLeadResponseError)

export const getGetJobLeadUrl = (id: number,) => {




  return `/api/job-leads/${id}`
}

export const getJobLead = async (id: number, options?: RequestInit): Promise<getJobLeadResponse> => {

  return apiClient<getJobLeadResponse>(getGetJobLeadUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobLeadQueryKey = (id: number,) => {
    return [
    `/api/job-leads/${id}`
    ] as const;
    }


export const getGetJobLeadQueryOptions = <TData = Awaited<ReturnType<typeof getJobLead>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLead>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobLeadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobLead>>> = ({ signal }) => getJobLead(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobLead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobLeadQueryResult = NonNullable<Awaited<ReturnType<typeof getJobLead>>>
export type GetJobLeadQueryError = void


export function useGetJobLead<TData = Awaited<ReturnType<typeof getJobLead>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobLead>>,
          TError,
          Awaited<ReturnType<typeof getJobLead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobLead<TData = Awaited<ReturnType<typeof getJobLead>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobLead>>,
          TError,
          Awaited<ReturnType<typeof getJobLead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobLead<TData = Awaited<ReturnType<typeof getJobLead>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLead>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetJobLead<TData = Awaited<ReturnType<typeof getJobLead>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobLead>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobLeadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateJobLeadResponse200 = {
  data: JobLeadDto
  status: 200
}

export type updateJobLeadResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateJobLeadResponse404 = {
  data: void
  status: 404
}

export type updateJobLeadResponseSuccess = (updateJobLeadResponse200) & {
  headers: Headers;
};
export type updateJobLeadResponseError = (updateJobLeadResponse400 | updateJobLeadResponse404) & {
  headers: Headers;
};

export type updateJobLeadResponse = (updateJobLeadResponseSuccess | updateJobLeadResponseError)

export const getUpdateJobLeadUrl = (id: number,) => {




  return `/api/job-leads/${id}`
}

export const updateJobLead = async (id: number,
    updateJobLeadRequest: UpdateJobLeadRequest, options?: RequestInit): Promise<updateJobLeadResponse> => {

  return apiClient<updateJobLeadResponse>(getUpdateJobLeadUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateJobLeadRequest)
  }
);}




export const getUpdateJobLeadMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJobLead>>, TError,{id: number;data: UpdateJobLeadRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateJobLead>>, TError,{id: number;data: UpdateJobLeadRequest}, TContext> => {

const mutationKey = ['updateJobLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateJobLead>>, {id: number;data: UpdateJobLeadRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateJobLead(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateJobLeadMutationResult = NonNullable<Awaited<ReturnType<typeof updateJobLead>>>
    export type UpdateJobLeadMutationBody = UpdateJobLeadRequest
    export type UpdateJobLeadMutationError = HttpValidationProblemDetails | void

    export const useUpdateJobLead = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJobLead>>, TError,{id: number;data: UpdateJobLeadRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateJobLead>>,
        TError,
        {id: number;data: UpdateJobLeadRequest},
        TContext
      > => {
      return useMutation(getUpdateJobLeadMutationOptions(options), queryClient);
    }
    export type deleteJobLeadResponse204 = {
  data: void
  status: 204
}

export type deleteJobLeadResponse404 = {
  data: void
  status: 404
}

export type deleteJobLeadResponseSuccess = (deleteJobLeadResponse204) & {
  headers: Headers;
};
export type deleteJobLeadResponseError = (deleteJobLeadResponse404) & {
  headers: Headers;
};

export type deleteJobLeadResponse = (deleteJobLeadResponseSuccess | deleteJobLeadResponseError)

export const getDeleteJobLeadUrl = (id: number,) => {




  return `/api/job-leads/${id}`
}

export const deleteJobLead = async (id: number, options?: RequestInit): Promise<deleteJobLeadResponse> => {

  return apiClient<deleteJobLeadResponse>(getDeleteJobLeadUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteJobLeadMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobLead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJobLead>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteJobLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJobLead>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteJobLead(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobLeadMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJobLead>>>

    export type DeleteJobLeadMutationError = void

    export const useDeleteJobLead = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobLead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteJobLead>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteJobLeadMutationOptions(options), queryClient);
    }
