/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getInterviewsResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getInterviewsResponseApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getInterviewsResponseDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetInterviewsResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getInterviewsResponseIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', getInterviewsResponseApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', getInterviewsResponseDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const GetInterviewsResponse = zod.array(GetInterviewsResponseItem)

export const createInterviewBodyApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createInterviewBodyDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateInterviewBody = zod.object({
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', createInterviewBodyApplicationIdRegExpTwo)]),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', createInterviewBodyDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "prepNotes": zod.string().nullable()
})

export const createInterviewResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createInterviewResponseApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const createInterviewResponseDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateInterviewResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createInterviewResponseIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', createInterviewResponseApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', createInterviewResponseDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const getUpcomingInterviewsResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getUpcomingInterviewsResponseApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getUpcomingInterviewsResponseDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetUpcomingInterviewsResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getUpcomingInterviewsResponseIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', getUpcomingInterviewsResponseApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', getUpcomingInterviewsResponseDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const GetUpcomingInterviewsResponse = zod.array(GetUpcomingInterviewsResponseItem)

export const GetInterviewParams = zod.object({
  "id": zod.number()
})

export const getInterviewResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getInterviewResponseApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getInterviewResponseDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetInterviewResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getInterviewResponseIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', getInterviewResponseApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', getInterviewResponseDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const UpdateInterviewParams = zod.object({
  "id": zod.number()
})

export const updateInterviewBodyDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateInterviewBody = zod.object({
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', updateInterviewBodyDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable()
})

export const updateInterviewResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateInterviewResponseApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateInterviewResponseDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateInterviewResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', updateInterviewResponseIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', updateInterviewResponseApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', updateInterviewResponseDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const DeleteInterviewParams = zod.object({
  "id": zod.number()
})

export const DeleteInterviewResponse = zod.void()

export const MarkInterviewCompletedParams = zod.object({
  "id": zod.number()
})

export const MarkInterviewCompletedBody = zod.object({
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable()
})

export const markInterviewCompletedResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markInterviewCompletedResponseApplicationIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const markInterviewCompletedResponseDurationMinutesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const MarkInterviewCompletedResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', markInterviewCompletedResponseIdRegExpTwo)]),
  "applicationId": zod.union([zod.number(),zod.stringFormat('int32', markInterviewCompletedResponseApplicationIdRegExpTwo)]),
  "companyName": zod.string(),
  "jobTitle": zod.string(),
  "roundType": zod.number(),
  "scheduledAtUtc": zod.iso.datetime({"offset":true}),
  "durationMinutes": zod.union([zod.number(),zod.stringFormat('int32', markInterviewCompletedResponseDurationMinutesRegExpTwo)]).nullable(),
  "interviewerName": zod.string().nullable(),
  "interviewerRole": zod.string().nullable(),
  "meetingUrl": zod.string().nullable(),
  "status": zod.number(),
  "prepNotes": zod.string().nullable(),
  "outcome": zod.number(),
  "feedback": zod.string().nullable(),
  "followUpRequired": zod.boolean(),
  "followUpAtUtc": zod.iso.datetime({"offset":true}).nullable(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

