/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInterviewRequest,
  HttpValidationProblemDetails,
  InterviewDto,
  MarkInterviewCompletedRequest,
  UpdateInterviewRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getInterviewsResponse200 = {
  data: InterviewDto[]
  status: 200
}

export type getInterviewsResponseSuccess = (getInterviewsResponse200) & {
  headers: Headers;
};
;

export type getInterviewsResponse = (getInterviewsResponseSuccess)

export const getGetInterviewsUrl = () => {




  return `/api/interviews`
}

export const getInterviews = async ( options?: RequestInit): Promise<getInterviewsResponse> => {

  return apiClient<getInterviewsResponse>(getGetInterviewsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInterviewsQueryKey = () => {
    return [
    `/api/interviews`
    ] as const;
    }


export const getGetInterviewsQueryOptions = <TData = Awaited<ReturnType<typeof getInterviews>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterviews>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterviewsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterviews>>> = ({ signal }) => getInterviews({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getInterviews>>>
export type GetInterviewsQueryError = unknown


export function useGetInterviews<TData = Awaited<ReturnType<typeof getInterviews>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterviews>>,
          TError,
          Awaited<ReturnType<typeof getInterviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterviews<TData = Awaited<ReturnType<typeof getInterviews>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterviews>>,
          TError,
          Awaited<ReturnType<typeof getInterviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterviews<TData = Awaited<ReturnType<typeof getInterviews>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterviews>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterviews<TData = Awaited<ReturnType<typeof getInterviews>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterviews>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterviewsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createInterviewResponse201 = {
  data: InterviewDto
  status: 201
}

export type createInterviewResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createInterviewResponse404 = {
  data: void
  status: 404
}

export type createInterviewResponseSuccess = (createInterviewResponse201) & {
  headers: Headers;
};
export type createInterviewResponseError = (createInterviewResponse400 | createInterviewResponse404) & {
  headers: Headers;
};

export type createInterviewResponse = (createInterviewResponseSuccess | createInterviewResponseError)

export const getCreateInterviewUrl = () => {




  return `/api/interviews`
}

export const createInterview = async (createInterviewRequest: CreateInterviewRequest, options?: RequestInit): Promise<createInterviewResponse> => {

  return apiClient<createInterviewResponse>(getCreateInterviewUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createInterviewRequest)
  }
);}




export const getCreateInterviewMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInterview>>, TError,{data: CreateInterviewRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createInterview>>, TError,{data: CreateInterviewRequest}, TContext> => {

const mutationKey = ['createInterview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInterview>>, {data: CreateInterviewRequest}> = (props) => {
          const {data} = props ?? {};

          return  createInterview(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInterviewMutationResult = NonNullable<Awaited<ReturnType<typeof createInterview>>>
    export type CreateInterviewMutationBody = CreateInterviewRequest
    export type CreateInterviewMutationError = HttpValidationProblemDetails | void

    export const useCreateInterview = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInterview>>, TError,{data: CreateInterviewRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInterview>>,
        TError,
        {data: CreateInterviewRequest},
        TContext
      > => {
      return useMutation(getCreateInterviewMutationOptions(options), queryClient);
    }
    export type getUpcomingInterviewsResponse200 = {
  data: InterviewDto[]
  status: 200
}

export type getUpcomingInterviewsResponseSuccess = (getUpcomingInterviewsResponse200) & {
  headers: Headers;
};
;

export type getUpcomingInterviewsResponse = (getUpcomingInterviewsResponseSuccess)

export const getGetUpcomingInterviewsUrl = () => {




  return `/api/interviews/upcoming`
}

export const getUpcomingInterviews = async ( options?: RequestInit): Promise<getUpcomingInterviewsResponse> => {

  return apiClient<getUpcomingInterviewsResponse>(getGetUpcomingInterviewsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUpcomingInterviewsQueryKey = () => {
    return [
    `/api/interviews/upcoming`
    ] as const;
    }


export const getGetUpcomingInterviewsQueryOptions = <TData = Awaited<ReturnType<typeof getUpcomingInterviews>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingInterviews>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUpcomingInterviewsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUpcomingInterviews>>> = ({ signal }) => getUpcomingInterviews({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUpcomingInterviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUpcomingInterviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getUpcomingInterviews>>>
export type GetUpcomingInterviewsQueryError = unknown


export function useGetUpcomingInterviews<TData = Awaited<ReturnType<typeof getUpcomingInterviews>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingInterviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingInterviews>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingInterviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingInterviews<TData = Awaited<ReturnType<typeof getUpcomingInterviews>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingInterviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingInterviews>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingInterviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingInterviews<TData = Awaited<ReturnType<typeof getUpcomingInterviews>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingInterviews>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUpcomingInterviews<TData = Awaited<ReturnType<typeof getUpcomingInterviews>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingInterviews>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUpcomingInterviewsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getInterviewResponse200 = {
  data: InterviewDto
  status: 200
}

export type getInterviewResponse404 = {
  data: void
  status: 404
}

export type getInterviewResponseSuccess = (getInterviewResponse200) & {
  headers: Headers;
};
export type getInterviewResponseError = (getInterviewResponse404) & {
  headers: Headers;
};

export type getInterviewResponse = (getInterviewResponseSuccess | getInterviewResponseError)

export const getGetInterviewUrl = (id: number,) => {




  return `/api/interviews/${id}`
}

export const getInterview = async (id: number, options?: RequestInit): Promise<getInterviewResponse> => {

  return apiClient<getInterviewResponse>(getGetInterviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInterviewQueryKey = (id: number,) => {
    return [
    `/api/interviews/${id}`
    ] as const;
    }


export const getGetInterviewQueryOptions = <TData = Awaited<ReturnType<typeof getInterview>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterview>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterviewQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterview>>> = ({ signal }) => getInterview(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterviewQueryResult = NonNullable<Awaited<ReturnType<typeof getInterview>>>
export type GetInterviewQueryError = void


export function useGetInterview<TData = Awaited<ReturnType<typeof getInterview>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterview>>,
          TError,
          Awaited<ReturnType<typeof getInterview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterview<TData = Awaited<ReturnType<typeof getInterview>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterview>>,
          TError,
          Awaited<ReturnType<typeof getInterview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterview<TData = Awaited<ReturnType<typeof getInterview>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterview>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterview<TData = Awaited<ReturnType<typeof getInterview>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterview>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterviewQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateInterviewResponse200 = {
  data: InterviewDto
  status: 200
}

export type updateInterviewResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateInterviewResponse404 = {
  data: void
  status: 404
}

export type updateInterviewResponseSuccess = (updateInterviewResponse200) & {
  headers: Headers;
};
export type updateInterviewResponseError = (updateInterviewResponse400 | updateInterviewResponse404) & {
  headers: Headers;
};

export type updateInterviewResponse = (updateInterviewResponseSuccess | updateInterviewResponseError)

export const getUpdateInterviewUrl = (id: number,) => {




  return `/api/interviews/${id}`
}

export const updateInterview = async (id: number,
    updateInterviewRequest: UpdateInterviewRequest, options?: RequestInit): Promise<updateInterviewResponse> => {

  return apiClient<updateInterviewResponse>(getUpdateInterviewUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateInterviewRequest)
  }
);}




export const getUpdateInterviewMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateInterview>>, TError,{id: number;data: UpdateInterviewRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateInterview>>, TError,{id: number;data: UpdateInterviewRequest}, TContext> => {

const mutationKey = ['updateInterview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateInterview>>, {id: number;data: UpdateInterviewRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateInterview(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateInterviewMutationResult = NonNullable<Awaited<ReturnType<typeof updateInterview>>>
    export type UpdateInterviewMutationBody = UpdateInterviewRequest
    export type UpdateInterviewMutationError = HttpValidationProblemDetails | void

    export const useUpdateInterview = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateInterview>>, TError,{id: number;data: UpdateInterviewRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateInterview>>,
        TError,
        {id: number;data: UpdateInterviewRequest},
        TContext
      > => {
      return useMutation(getUpdateInterviewMutationOptions(options), queryClient);
    }
    export type deleteInterviewResponse204 = {
  data: void
  status: 204
}

export type deleteInterviewResponse404 = {
  data: void
  status: 404
}

export type deleteInterviewResponseSuccess = (deleteInterviewResponse204) & {
  headers: Headers;
};
export type deleteInterviewResponseError = (deleteInterviewResponse404) & {
  headers: Headers;
};

export type deleteInterviewResponse = (deleteInterviewResponseSuccess | deleteInterviewResponseError)

export const getDeleteInterviewUrl = (id: number,) => {




  return `/api/interviews/${id}`
}

export const deleteInterview = async (id: number, options?: RequestInit): Promise<deleteInterviewResponse> => {

  return apiClient<deleteInterviewResponse>(getDeleteInterviewUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteInterviewMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteInterview>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteInterview>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteInterview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteInterview>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteInterview(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteInterviewMutationResult = NonNullable<Awaited<ReturnType<typeof deleteInterview>>>

    export type DeleteInterviewMutationError = void

    export const useDeleteInterview = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteInterview>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteInterview>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteInterviewMutationOptions(options), queryClient);
    }
    export type markInterviewCompletedResponse200 = {
  data: InterviewDto
  status: 200
}

export type markInterviewCompletedResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type markInterviewCompletedResponse404 = {
  data: void
  status: 404
}

export type markInterviewCompletedResponseSuccess = (markInterviewCompletedResponse200) & {
  headers: Headers;
};
export type markInterviewCompletedResponseError = (markInterviewCompletedResponse400 | markInterviewCompletedResponse404) & {
  headers: Headers;
};

export type markInterviewCompletedResponse = (markInterviewCompletedResponseSuccess | markInterviewCompletedResponseError)

export const getMarkInterviewCompletedUrl = (id: number,) => {




  return `/api/interviews/${id}/mark-completed`
}

export const markInterviewCompleted = async (id: number,
    markInterviewCompletedRequest: MarkInterviewCompletedRequest, options?: RequestInit): Promise<markInterviewCompletedResponse> => {

  return apiClient<markInterviewCompletedResponse>(getMarkInterviewCompletedUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(markInterviewCompletedRequest)
  }
);}




export const getMarkInterviewCompletedMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markInterviewCompleted>>, TError,{id: number;data: MarkInterviewCompletedRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof markInterviewCompleted>>, TError,{id: number;data: MarkInterviewCompletedRequest}, TContext> => {

const mutationKey = ['markInterviewCompleted'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markInterviewCompleted>>, {id: number;data: MarkInterviewCompletedRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  markInterviewCompleted(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkInterviewCompletedMutationResult = NonNullable<Awaited<ReturnType<typeof markInterviewCompleted>>>
    export type MarkInterviewCompletedMutationBody = MarkInterviewCompletedRequest
    export type MarkInterviewCompletedMutationError = HttpValidationProblemDetails | void

    export const useMarkInterviewCompleted = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markInterviewCompleted>>, TError,{id: number;data: MarkInterviewCompletedRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markInterviewCompleted>>,
        TError,
        {id: number;data: MarkInterviewCompletedRequest},
        TContext
      > => {
      return useMutation(getMarkInterviewCompletedMutationOptions(options), queryClient);
    }
