/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateResumeVariantRequest,
  HttpValidationProblemDetails,
  ResumeVariantDto,
  UpdateResumeVariantRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getResumeVariantsResponse200 = {
  data: ResumeVariantDto[]
  status: 200
}

export type getResumeVariantsResponseSuccess = (getResumeVariantsResponse200) & {
  headers: Headers;
};
;

export type getResumeVariantsResponse = (getResumeVariantsResponseSuccess)

export const getGetResumeVariantsUrl = () => {




  return `/api/resume-variants`
}

export const getResumeVariants = async ( options?: RequestInit): Promise<getResumeVariantsResponse> => {

  return apiClient<getResumeVariantsResponse>(getGetResumeVariantsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetResumeVariantsQueryKey = () => {
    return [
    `/api/resume-variants`
    ] as const;
    }


export const getGetResumeVariantsQueryOptions = <TData = Awaited<ReturnType<typeof getResumeVariants>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariants>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResumeVariantsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResumeVariants>>> = ({ signal }) => getResumeVariants({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResumeVariants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetResumeVariantsQueryResult = NonNullable<Awaited<ReturnType<typeof getResumeVariants>>>
export type GetResumeVariantsQueryError = unknown


export function useGetResumeVariants<TData = Awaited<ReturnType<typeof getResumeVariants>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResumeVariants>>,
          TError,
          Awaited<ReturnType<typeof getResumeVariants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResumeVariants<TData = Awaited<ReturnType<typeof getResumeVariants>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResumeVariants>>,
          TError,
          Awaited<ReturnType<typeof getResumeVariants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResumeVariants<TData = Awaited<ReturnType<typeof getResumeVariants>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariants>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetResumeVariants<TData = Awaited<ReturnType<typeof getResumeVariants>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariants>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetResumeVariantsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createResumeVariantResponse201 = {
  data: ResumeVariantDto
  status: 201
}

export type createResumeVariantResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createResumeVariantResponseSuccess = (createResumeVariantResponse201) & {
  headers: Headers;
};
export type createResumeVariantResponseError = (createResumeVariantResponse400) & {
  headers: Headers;
};

export type createResumeVariantResponse = (createResumeVariantResponseSuccess | createResumeVariantResponseError)

export const getCreateResumeVariantUrl = () => {




  return `/api/resume-variants`
}

export const createResumeVariant = async (createResumeVariantRequest: CreateResumeVariantRequest, options?: RequestInit): Promise<createResumeVariantResponse> => {

  return apiClient<createResumeVariantResponse>(getCreateResumeVariantUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createResumeVariantRequest)
  }
);}




export const getCreateResumeVariantMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResumeVariant>>, TError,{data: CreateResumeVariantRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createResumeVariant>>, TError,{data: CreateResumeVariantRequest}, TContext> => {

const mutationKey = ['createResumeVariant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createResumeVariant>>, {data: CreateResumeVariantRequest}> = (props) => {
          const {data} = props ?? {};

          return  createResumeVariant(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateResumeVariantMutationResult = NonNullable<Awaited<ReturnType<typeof createResumeVariant>>>
    export type CreateResumeVariantMutationBody = CreateResumeVariantRequest
    export type CreateResumeVariantMutationError = HttpValidationProblemDetails

    export const useCreateResumeVariant = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResumeVariant>>, TError,{data: CreateResumeVariantRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createResumeVariant>>,
        TError,
        {data: CreateResumeVariantRequest},
        TContext
      > => {
      return useMutation(getCreateResumeVariantMutationOptions(options), queryClient);
    }
    export type getResumeVariantResponse200 = {
  data: ResumeVariantDto
  status: 200
}

export type getResumeVariantResponse404 = {
  data: void
  status: 404
}

export type getResumeVariantResponseSuccess = (getResumeVariantResponse200) & {
  headers: Headers;
};
export type getResumeVariantResponseError = (getResumeVariantResponse404) & {
  headers: Headers;
};

export type getResumeVariantResponse = (getResumeVariantResponseSuccess | getResumeVariantResponseError)

export const getGetResumeVariantUrl = (id: number,) => {




  return `/api/resume-variants/${id}`
}

export const getResumeVariant = async (id: number, options?: RequestInit): Promise<getResumeVariantResponse> => {

  return apiClient<getResumeVariantResponse>(getGetResumeVariantUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetResumeVariantQueryKey = (id: number,) => {
    return [
    `/api/resume-variants/${id}`
    ] as const;
    }


export const getGetResumeVariantQueryOptions = <TData = Awaited<ReturnType<typeof getResumeVariant>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariant>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResumeVariantQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResumeVariant>>> = ({ signal }) => getResumeVariant(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResumeVariant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetResumeVariantQueryResult = NonNullable<Awaited<ReturnType<typeof getResumeVariant>>>
export type GetResumeVariantQueryError = void


export function useGetResumeVariant<TData = Awaited<ReturnType<typeof getResumeVariant>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResumeVariant>>,
          TError,
          Awaited<ReturnType<typeof getResumeVariant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResumeVariant<TData = Awaited<ReturnType<typeof getResumeVariant>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResumeVariant>>,
          TError,
          Awaited<ReturnType<typeof getResumeVariant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResumeVariant<TData = Awaited<ReturnType<typeof getResumeVariant>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariant>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetResumeVariant<TData = Awaited<ReturnType<typeof getResumeVariant>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResumeVariant>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetResumeVariantQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateResumeVariantResponse200 = {
  data: ResumeVariantDto
  status: 200
}

export type updateResumeVariantResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateResumeVariantResponse404 = {
  data: void
  status: 404
}

export type updateResumeVariantResponseSuccess = (updateResumeVariantResponse200) & {
  headers: Headers;
};
export type updateResumeVariantResponseError = (updateResumeVariantResponse400 | updateResumeVariantResponse404) & {
  headers: Headers;
};

export type updateResumeVariantResponse = (updateResumeVariantResponseSuccess | updateResumeVariantResponseError)

export const getUpdateResumeVariantUrl = (id: number,) => {




  return `/api/resume-variants/${id}`
}

export const updateResumeVariant = async (id: number,
    updateResumeVariantRequest: UpdateResumeVariantRequest, options?: RequestInit): Promise<updateResumeVariantResponse> => {

  return apiClient<updateResumeVariantResponse>(getUpdateResumeVariantUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateResumeVariantRequest)
  }
);}




export const getUpdateResumeVariantMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResumeVariant>>, TError,{id: number;data: UpdateResumeVariantRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateResumeVariant>>, TError,{id: number;data: UpdateResumeVariantRequest}, TContext> => {

const mutationKey = ['updateResumeVariant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateResumeVariant>>, {id: number;data: UpdateResumeVariantRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateResumeVariant(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateResumeVariantMutationResult = NonNullable<Awaited<ReturnType<typeof updateResumeVariant>>>
    export type UpdateResumeVariantMutationBody = UpdateResumeVariantRequest
    export type UpdateResumeVariantMutationError = HttpValidationProblemDetails | void

    export const useUpdateResumeVariant = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResumeVariant>>, TError,{id: number;data: UpdateResumeVariantRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateResumeVariant>>,
        TError,
        {id: number;data: UpdateResumeVariantRequest},
        TContext
      > => {
      return useMutation(getUpdateResumeVariantMutationOptions(options), queryClient);
    }
    export type deleteResumeVariantResponse204 = {
  data: void
  status: 204
}

export type deleteResumeVariantResponse404 = {
  data: void
  status: 404
}

export type deleteResumeVariantResponseSuccess = (deleteResumeVariantResponse204) & {
  headers: Headers;
};
export type deleteResumeVariantResponseError = (deleteResumeVariantResponse404) & {
  headers: Headers;
};

export type deleteResumeVariantResponse = (deleteResumeVariantResponseSuccess | deleteResumeVariantResponseError)

export const getDeleteResumeVariantUrl = (id: number,) => {




  return `/api/resume-variants/${id}`
}

export const deleteResumeVariant = async (id: number, options?: RequestInit): Promise<deleteResumeVariantResponse> => {

  return apiClient<deleteResumeVariantResponse>(getDeleteResumeVariantUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteResumeVariantMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResumeVariant>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteResumeVariant>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteResumeVariant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteResumeVariant>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteResumeVariant(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteResumeVariantMutationResult = NonNullable<Awaited<ReturnType<typeof deleteResumeVariant>>>

    export type DeleteResumeVariantMutationError = void

    export const useDeleteResumeVariant = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResumeVariant>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteResumeVariant>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteResumeVariantMutationOptions(options), queryClient);
    }
    export type makeResumeVariantDefaultResponse200 = {
  data: ResumeVariantDto
  status: 200
}

export type makeResumeVariantDefaultResponse404 = {
  data: void
  status: 404
}

export type makeResumeVariantDefaultResponseSuccess = (makeResumeVariantDefaultResponse200) & {
  headers: Headers;
};
export type makeResumeVariantDefaultResponseError = (makeResumeVariantDefaultResponse404) & {
  headers: Headers;
};

export type makeResumeVariantDefaultResponse = (makeResumeVariantDefaultResponseSuccess | makeResumeVariantDefaultResponseError)

export const getMakeResumeVariantDefaultUrl = (id: number,) => {




  return `/api/resume-variants/${id}/make-default`
}

export const makeResumeVariantDefault = async (id: number, options?: RequestInit): Promise<makeResumeVariantDefaultResponse> => {

  return apiClient<makeResumeVariantDefaultResponse>(getMakeResumeVariantDefaultUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getMakeResumeVariantDefaultMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof makeResumeVariantDefault>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof makeResumeVariantDefault>>, TError,{id: number}, TContext> => {

const mutationKey = ['makeResumeVariantDefault'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof makeResumeVariantDefault>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  makeResumeVariantDefault(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MakeResumeVariantDefaultMutationResult = NonNullable<Awaited<ReturnType<typeof makeResumeVariantDefault>>>

    export type MakeResumeVariantDefaultMutationError = void

    export const useMakeResumeVariantDefault = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof makeResumeVariantDefault>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof makeResumeVariantDefault>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getMakeResumeVariantDefaultMutationOptions(options), queryClient);
    }
