/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * CareerOps.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getResumeVariantsResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetResumeVariantsResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getResumeVariantsResponseIdRegExpTwo)]),
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "isDefault": zod.boolean(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const GetResumeVariantsResponse = zod.array(GetResumeVariantsResponseItem)

export const CreateResumeVariantBody = zod.object({
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const createResumeVariantResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const CreateResumeVariantResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', createResumeVariantResponseIdRegExpTwo)]),
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "isDefault": zod.boolean(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const GetResumeVariantParams = zod.object({
  "id": zod.number()
})

export const getResumeVariantResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetResumeVariantResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', getResumeVariantResponseIdRegExpTwo)]),
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "isDefault": zod.boolean(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const UpdateResumeVariantParams = zod.object({
  "id": zod.number()
})

export const UpdateResumeVariantBody = zod.object({
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable()
})

export const updateResumeVariantResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateResumeVariantResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', updateResumeVariantResponseIdRegExpTwo)]),
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "isDefault": zod.boolean(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

export const DeleteResumeVariantParams = zod.object({
  "id": zod.number()
})

export const DeleteResumeVariantResponse = zod.void()

export const MakeResumeVariantDefaultParams = zod.object({
  "id": zod.number()
})

export const makeResumeVariantDefaultResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const MakeResumeVariantDefaultResponse = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', makeResumeVariantDefaultResponseIdRegExpTwo)]),
  "name": zod.string(),
  "targetRole": zod.string().nullable(),
  "summary": zod.string().nullable(),
  "notes": zod.string().nullable(),
  "isDefault": zod.boolean(),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})

