/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FollowUpTaskDto,
  ListFollowUpTasksParams,
  UpdateFollowUpTaskRequest
} from '../model';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listFollowUpTasksResponse200 = {
  data: FollowUpTaskDto[]
  status: 200
}

export type listFollowUpTasksResponseSuccess = (listFollowUpTasksResponse200) & {
  headers: Headers;
};
;

export type listFollowUpTasksResponse = (listFollowUpTasksResponseSuccess)

export const getListFollowUpTasksUrl = (params?: ListFollowUpTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/follow-up-tasks?${stringifiedParams}` : `/api/follow-up-tasks`
}

export const listFollowUpTasks = async (params?: ListFollowUpTasksParams, options?: RequestInit): Promise<listFollowUpTasksResponse> => {

  return apiClient<listFollowUpTasksResponse>(getListFollowUpTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFollowUpTasksQueryKey = (params?: ListFollowUpTasksParams,) => {
    return [
    `/api/follow-up-tasks`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFollowUpTasksQueryOptions = <TData = Awaited<ReturnType<typeof listFollowUpTasks>>, TError = unknown>(params?: ListFollowUpTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFollowUpTasks>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFollowUpTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFollowUpTasks>>> = ({ signal }) => listFollowUpTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFollowUpTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFollowUpTasksQueryResult = NonNullable<Awaited<ReturnType<typeof listFollowUpTasks>>>
export type ListFollowUpTasksQueryError = unknown


export function useListFollowUpTasks<TData = Awaited<ReturnType<typeof listFollowUpTasks>>, TError = unknown>(
 params: undefined |  ListFollowUpTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFollowUpTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFollowUpTasks>>,
          TError,
          Awaited<ReturnType<typeof listFollowUpTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFollowUpTasks<TData = Awaited<ReturnType<typeof listFollowUpTasks>>, TError = unknown>(
 params?: ListFollowUpTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFollowUpTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFollowUpTasks>>,
          TError,
          Awaited<ReturnType<typeof listFollowUpTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFollowUpTasks<TData = Awaited<ReturnType<typeof listFollowUpTasks>>, TError = unknown>(
 params?: ListFollowUpTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFollowUpTasks>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListFollowUpTasks<TData = Awaited<ReturnType<typeof listFollowUpTasks>>, TError = unknown>(
 params?: ListFollowUpTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFollowUpTasks>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFollowUpTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateFollowUpTaskResponse200 = {
  data: void
  status: 200
}

export type updateFollowUpTaskResponseSuccess = (updateFollowUpTaskResponse200) & {
  headers: Headers;
};
;

export type updateFollowUpTaskResponse = (updateFollowUpTaskResponseSuccess)

export const getUpdateFollowUpTaskUrl = (id: number,) => {




  return `/api/follow-up-tasks/${id}`
}

export const updateFollowUpTask = async (id: number,
    updateFollowUpTaskRequest: UpdateFollowUpTaskRequest, options?: RequestInit): Promise<updateFollowUpTaskResponse> => {

  return apiClient<updateFollowUpTaskResponse>(getUpdateFollowUpTaskUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateFollowUpTaskRequest)
  }
);}





export const getUpdateFollowUpTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFollowUpTask>>, TError,{id: number;data: UpdateFollowUpTaskRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateFollowUpTask>>, TError,{id: number;data: UpdateFollowUpTaskRequest}, TContext> => {

const mutationKey = ['updateFollowUpTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFollowUpTask>>, {id: number;data: UpdateFollowUpTaskRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFollowUpTask(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFollowUpTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateFollowUpTask>>>
    export type UpdateFollowUpTaskMutationBody = UpdateFollowUpTaskRequest
    export type UpdateFollowUpTaskMutationError = unknown

    export const useUpdateFollowUpTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFollowUpTask>>, TError,{id: number;data: UpdateFollowUpTaskRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFollowUpTask>>,
        TError,
        {id: number;data: UpdateFollowUpTaskRequest},
        TContext
      > => {
      return useMutation(getUpdateFollowUpTaskMutationOptions(options), queryClient);
    }
    export type deleteFollowUpTaskResponse200 = {
  data: void
  status: 200
}

export type deleteFollowUpTaskResponseSuccess = (deleteFollowUpTaskResponse200) & {
  headers: Headers;
};
;

export type deleteFollowUpTaskResponse = (deleteFollowUpTaskResponseSuccess)

export const getDeleteFollowUpTaskUrl = (id: number,) => {




  return `/api/follow-up-tasks/${id}`
}

export const deleteFollowUpTask = async (id: number, options?: RequestInit): Promise<deleteFollowUpTaskResponse> => {

  return apiClient<deleteFollowUpTaskResponse>(getDeleteFollowUpTaskUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFollowUpTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFollowUpTask>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFollowUpTask>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteFollowUpTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFollowUpTask>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteFollowUpTask(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFollowUpTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFollowUpTask>>>

    export type DeleteFollowUpTaskMutationError = unknown

    export const useDeleteFollowUpTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFollowUpTask>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFollowUpTask>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteFollowUpTaskMutationOptions(options), queryClient);
    }
    export type completeFollowUpTaskResponse200 = {
  data: void
  status: 200
}

export type completeFollowUpTaskResponseSuccess = (completeFollowUpTaskResponse200) & {
  headers: Headers;
};
;

export type completeFollowUpTaskResponse = (completeFollowUpTaskResponseSuccess)

export const getCompleteFollowUpTaskUrl = (id: number,) => {




  return `/api/follow-up-tasks/${id}/complete`
}

export const completeFollowUpTask = async (id: number, options?: RequestInit): Promise<completeFollowUpTaskResponse> => {

  return apiClient<completeFollowUpTaskResponse>(getCompleteFollowUpTaskUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCompleteFollowUpTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeFollowUpTask>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof completeFollowUpTask>>, TError,{id: number}, TContext> => {

const mutationKey = ['completeFollowUpTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeFollowUpTask>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  completeFollowUpTask(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteFollowUpTaskMutationResult = NonNullable<Awaited<ReturnType<typeof completeFollowUpTask>>>

    export type CompleteFollowUpTaskMutationError = unknown

    export const useCompleteFollowUpTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeFollowUpTask>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeFollowUpTask>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCompleteFollowUpTaskMutationOptions(options), queryClient);
    }
    export type skipFollowUpTaskResponse200 = {
  data: void
  status: 200
}

export type skipFollowUpTaskResponseSuccess = (skipFollowUpTaskResponse200) & {
  headers: Headers;
};
;

export type skipFollowUpTaskResponse = (skipFollowUpTaskResponseSuccess)

export const getSkipFollowUpTaskUrl = (id: number,) => {




  return `/api/follow-up-tasks/${id}/skip`
}

export const skipFollowUpTask = async (id: number, options?: RequestInit): Promise<skipFollowUpTaskResponse> => {

  return apiClient<skipFollowUpTaskResponse>(getSkipFollowUpTaskUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSkipFollowUpTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skipFollowUpTask>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof skipFollowUpTask>>, TError,{id: number}, TContext> => {

const mutationKey = ['skipFollowUpTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof skipFollowUpTask>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  skipFollowUpTask(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SkipFollowUpTaskMutationResult = NonNullable<Awaited<ReturnType<typeof skipFollowUpTask>>>

    export type SkipFollowUpTaskMutationError = unknown

    export const useSkipFollowUpTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skipFollowUpTask>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof skipFollowUpTask>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getSkipFollowUpTaskMutationOptions(options), queryClient);
    }
