/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * CareerOps.Presentation | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const listFollowUpTasksQueryJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const ListFollowUpTasksQueryParams = zod.object({
  "status": zod.enum(['Pending', 'Completed', 'Skipped']).optional(),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', listFollowUpTasksQueryJobIdRegExpTwo)]).optional(),
  "due": zod.string().optional()
})

export const listFollowUpTasksResponseIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const listFollowUpTasksResponseJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const listFollowUpTasksResponseJobActivityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const ListFollowUpTasksResponseItem = zod.object({
  "id": zod.union([zod.number(),zod.stringFormat('int32', listFollowUpTasksResponseIdRegExpTwo)]),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', listFollowUpTasksResponseJobIdRegExpTwo)]).nullable(),
  "jobTitle": zod.string().nullable(),
  "jobActivityId": zod.union([zod.number(),zod.stringFormat('int32', listFollowUpTasksResponseJobActivityIdRegExpTwo)]).nullable(),
  "jobActivityLabel": zod.string().nullable(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "status": zod.enum(['Pending', 'Completed', 'Skipped']),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "createdAtUtc": zod.iso.datetime({"offset":true}),
  "updatedAtUtc": zod.iso.datetime({"offset":true})
})
export const ListFollowUpTasksResponse = zod.array(ListFollowUpTasksResponseItem)

export const UpdateFollowUpTaskParams = zod.object({
  "id": zod.number()
})

export const updateFollowUpTaskBodyJobIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const updateFollowUpTaskBodyJobActivityIdRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const UpdateFollowUpTaskBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "dueAtUtc": zod.iso.datetime({"offset":true}),
  "priority": zod.enum(['Low', 'Medium', 'High']),
  "jobId": zod.union([zod.number(),zod.stringFormat('int32', updateFollowUpTaskBodyJobIdRegExpTwo)]).nullable(),
  "jobActivityId": zod.union([zod.number(),zod.stringFormat('int32', updateFollowUpTaskBodyJobActivityIdRegExpTwo)]).nullable()
})

export const UpdateFollowUpTaskResponse = zod.unknown()

export const DeleteFollowUpTaskParams = zod.object({
  "id": zod.number()
})

export const DeleteFollowUpTaskResponse = zod.unknown()

export const CompleteFollowUpTaskParams = zod.object({
  "id": zod.number()
})

export const CompleteFollowUpTaskResponse = zod.unknown()

export const SkipFollowUpTaskParams = zod.object({
  "id": zod.number()
})

export const SkipFollowUpTaskResponse = zod.unknown()

